import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {database} from '../scripts/db.mjs';
import worker,{dayBounds} from '../src/worker.js';
import {hmac,validateTelegram} from '../src/auth.js';
const migration=readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8');
function setup(){const DB=database();DB.sqlite.exec(migration);DB.sqlite.exec("INSERT INTO memberships VALUES('nail','9002')");const env={DB,DEV_MODE:'true',SUPERADMIN_IDS:'9001'};return {DB,env,async request(path,method='GET',data,role='client'){const r=await worker.fetch(new Request('http://localhost/api'+path,{method,headers:{'x-demo-role':role,'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})}),env);return {status:r.status,data:await r.json()}}}}
const tomorrow=()=>new Date(Date.now()+10800000+86400000).toISOString().slice(0,10);
async function makeBooking(t,extra={}){const slots=await t.request('/slots?company=nail&service=nail-1&date='+tomorrow());return t.request('/bookings','POST',{company_id:'nail',service_id:'nail-1',starts_at:slots.data[0],name:'Тест Клиент',phone:'+7 999 000-00-00',request_key:crypto.randomUUID(),...extra})}
test('Telegram signature, expiry and tamper protection',async()=>{const token='test:secret',params=new URLSearchParams({user:JSON.stringify({id:12345,first_name:'Тест'}),auth_date:'1000',query_id:'abc'});const sign=async p=>{const data=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');return Buffer.from(await hmac(await hmac('WebAppData',token),data)).toString('hex')};params.set('hash',await sign(params));assert.equal((await validateTelegram(params.toString(),token,1050)).id,'12345');await assert.rejects(validateTelegram(params.toString(),token,5000));params.set('user',JSON.stringify({id:9999}));await assert.rejects(validateTelegram(params.toString(),token,1050));});
test('production rejects forged demo role',async()=>{const t=setup();delete t.env.DEV_MODE;const r=await t.request('/me');assert.equal(r.status,401);});
test('demo mode is restricted to localhost',async()=>{const t=setup();const r=await worker.fetch(new Request('https://example.com/api/me',{headers:{'x-demo-role':'owner'}}),t.env);assert.equal(r.status,401)});
test('client cannot read company bookings or change company settings',async()=>{const t=setup();assert.equal((await t.request('/bookings?scope=company&company=nail')).status,403);assert.equal((await t.request('/companies/nail','PATCH',{})).status,403)});
test('company admin cannot access another tenant; owner can',async()=>{const t=setup();assert.equal((await t.request('/bookings?scope=company&company=auto','GET',null,'company')).status,403);assert.equal((await t.request('/bookings?scope=company&company=auto','GET',null,'owner')).status,200)});
test('server derives prices; repeated request is idempotent; overlaps fail',async()=>{const t=setup(),key=crypto.randomUUID(),first=await makeBooking(t,{request_key:key,price:1});assert.equal(first.status,201);assert.equal(first.data.price,2400);const duplicate=await makeBooking(t,{request_key:key});assert.equal(duplicate.data.id,first.data.id);const conflict=await makeBooking(t,{starts_at:first.data.starts_at+1800});assert.equal(conflict.status,409);const availability=await t.request('/slots?company=nail&service=nail-1&date='+tomorrow());assert.ok(!availability.data.includes(first.data.starts_at));assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) AS n FROM bookings').get().n,1);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) AS n FROM outbox').get().n,2)});
test('cancel releases slot and cannot be resurrected',async()=>{const t=setup(),b=await makeBooking(t);assert.equal((await t.request('/bookings/'+b.data.id,'PATCH',{status:'cancelled'})).status,200);const slots=await t.request('/slots?company=nail&service=nail-1&date='+tomorrow());assert.ok(slots.data.includes(b.data.starts_at));assert.equal((await t.request('/bookings/'+b.data.id,'PATCH',{status:'confirmed'},'company')).status,409)});
test('only company can confirm; cannot complete future appointment',async()=>{const t=setup(),b=await makeBooking(t);assert.equal((await t.request('/bookings/'+b.data.id,'PATCH',{status:'confirmed'})).status,403);assert.equal((await t.request('/bookings/'+b.data.id,'PATCH',{status:'confirmed'},'company')).status,200);assert.equal((await t.request('/bookings/'+b.data.id,'PATCH',{status:'done'},'company')).status,400)});
test('service tenant, invalid dates and expired slots are rejected',async()=>{const t=setup();assert.equal((await makeBooking(t,{service_id:'auto-1'})).status,400);assert.equal((await makeBooking(t,{starts_at:12345})).status,400);assert.throws(()=>dayBounds('2026-02-31'));assert.throws(()=>dayBounds('bad'))});
test('cleaning requires job details and own service',async()=>{const t=setup();const slots=await t.request('/slots?company=clean&service=clean-1&date='+tomorrow());const data={company_id:'clean',service_id:'clean-1',starts_at:slots.data[0],name:'Тест',phone:'+7 999 000-00-00',request_key:crypto.randomUUID()};assert.equal((await t.request('/bookings','POST',data)).status,400);assert.equal((await t.request('/bookings','POST',{...data,details:'Тестовый адрес, 50 м²'})).status,201)});
const registration={name:'Мастер Анна',category:'beauty',service_name:'Маникюр',price:1800,duration:60,open_hour:9,close_hour:20};
test('master registration is isolated and retry safe; public links expose only business data',async()=>{const t=setup();const a=await t.request('/register','POST',registration);assert.equal(a.status,201);const id=a.data.id;assert.equal((await t.request('/register','POST',{...registration,name:'Повтор'})).data.id,id);assert.equal((await t.request('/companies')).data.length,1);assert.equal((await t.request('/companies','GET',null,'company')).data.length,1);assert.equal((await t.request('/companies/'+id)).data.name,'Мастер Анна');assert.equal((await t.request('/bookings?scope=company&company='+id,'GET',null,'company')).status,403);const publicResponse=await worker.fetch(new Request('https://example.com/api/companies/'+id),t.env);assert.equal(publicResponse.status,200);assert.ok(!(await publicResponse.json()).bookings);assert.equal((await worker.fetch(new Request('https://example.com/api/companies'),t.env)).status,401);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM services WHERE company_id=?').get(id).n,1)});
test('new master services and client bookings preserve permissions and notifications',async()=>{const t=setup(),id=(await t.request('/register','POST',registration)).data.id;const service={company_id:id,name:'Педикюр',price:2200,duration:90,request_key:crypto.randomUUID()};assert.equal((await t.request('/services','POST',service,'company')).status,403);const s=await t.request('/services','POST',service);assert.equal(s.status,201);assert.equal((await t.request('/services','POST',service)).data.id,s.data.id);const slots=await t.request('/slots?company='+id+'&service='+s.data.id+'&date='+tomorrow());const b=await t.request('/bookings','POST',{company_id:id,service_id:s.data.id,starts_at:slots.data[0],name:'Клиент',phone:'+79990000000',request_key:crypto.randomUUID()},'company');assert.equal(b.status,201);assert.equal((await t.request('/bookings')).data.length,0);assert.equal((await t.request('/bookings?scope=company&company='+id)).data.length,1);assert.equal((await t.request('/bookings/'+b.data.id,'PATCH',{status:'confirmed'})).status,200);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM outbox WHERE chat_id=?').get('9003').n>0,true)});
