import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {database} from '../scripts/db.mjs';import worker,{deliver} from '../src/worker.js';import {ensureSchema} from '../src/v2.js';import {hmac} from '../src/auth.js';import {botEntry} from '../src/bot-entry.js';import {config,enabled} from '../src/v10.js';import {fromLocal,localDate,dateShift} from '../src/v3.js';import {createReview} from '../src/v7.js';
globalThis.fetch=async()=>Response.json({ok:true,result:{message_id:101}});
const token='test-only-token',now=()=>Math.floor(Date.now()/1000);
async function setup(){const DB=database();DB.sqlite.exec(fs.readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'));DB.sqlite.exec("INSERT INTO memberships VALUES('nail','9002'),('auto','9004')");await ensureSchema(DB);const env={DB,BOT_TOKEN:token,SUPERADMIN_IDS:'9001,9005',APP_URL:'https://example.com'};
 const headers=async id=>{const p=new URLSearchParams({auth_date:String(now()),user:JSON.stringify({id:Number(id),first_name:'User '+id,username:'user_'+id,allows_write_to_pm:true})});const s=[...p].sort(([a],[b])=>a<b?-1:1).map(([k,v])=>`${k}=${v}`).join('\n');p.set('hash',Buffer.from(await hmac(await hmac('WebAppData',token),s)).toString('hex'));return {'Content-Type':'application/json','X-Telegram-Init-Data':p.toString()}};
 const req=async(path,method='GET',data,id='9002')=>{const r=await worker.fetch(new Request('https://example.com/api'+path,{method,headers:await headers(id),...(data?{body:JSON.stringify(data)}:{})}),env);return {status:r.status,data:await r.json()}};
 const set=async(key,value)=>req('/v10/admin/config','POST',{key,value,confirm:true},'9001');
 const book=async(extra={},id='9003')=>{const d=dateShift(localDate(),3),slots=(await req('/slots?company=nail&service=nail-1&date='+d,'GET',null,id)).data;return req('/bookings','POST',{company_id:'nail',service_id:'nail-1',starts_at:slots[0],name:'Client',phone:'+79990000001',request_key:crypto.randomUUID(),...extra},id)};
 return {DB,env,req,set,book};}

test('v10 configuration requires main admin, validation and explicit confirmation; survives wrapper restart',async()=>{const t=await setup();for(const id of ['9002','9003','9004','9005'])assert.equal((await t.req('/v10/admin/config','GET',null,id)).status,403);assert.equal((await t.req('/v10/admin/config','POST',{key:'cancel_hours',value:12},'9001')).status,400);assert.equal((await t.set('cancel_hours',-1)).status,400);assert.equal((await t.set('cancel_hours',24)).status,200);assert.equal((await config(t.DB)).cancel_hours,24);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM admin_audit').get().n,1);assert.equal((await t.req('/v10/admin/config','GET',null,'9001')).data.cancel_hours,24)});

test('client cancellation boundary is strictly greater than 24h and cannot be bypassed with specialist options',async()=>{const t=await setup(),r=await t.book();assert.equal(r.status,201);const b=r.data,real=Date.now;try{Date.now=()=>(b.starts_at-86400)*1000;assert.equal((await t.req('/bookings/'+b.id,'PATCH',{status:'cancelled'},'9003')).status,403);Date.now=()=>(b.starts_at-86401)*1000;assert.equal((await t.req('/bookings/'+b.id,'PATCH',{status:'cancelled'},'9003')).status,200)}finally{Date.now=real}assert.equal(t.DB.sqlite.prepare('SELECT status FROM bookings WHERE id=?').get(b.id).status,'cancelled')});

test('specialists and clients cannot mutate objects or admin state belonging to another account',async()=>{const t=await setup(),b=(await t.book()).data;assert.equal((await t.req('/bookings/'+b.id,'PATCH',{status:'confirmed'},'9004')).status,403);assert.equal((await t.req('/bookings/'+b.id,'PATCH',{status:'cancelled'},'9006')).status,403);assert.equal((await t.req('/bookings?scope=company&company=nail','GET',null,'9004')).status,403);assert.equal((await t.req('/v10/admin/user','POST',{user_id:'9003',blocked:true,confirm:true},'9002')).status,403)});

test('parallel client requests reserve a slot only once',async()=>{const t=await setup(),start=(await t.req('/slots?company=nail&service=nail-1&date='+dateShift(localDate(),3))).data[0];const rows=await Promise.all([t.book({starts_at:start},'9003'),t.book({starts_at:start},'9006')]);assert.deepEqual(rows.map(r=>r.status).sort(),[201,409]);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM bookings').get().n,1)});

test('manual booking with known invited client keeps identity and queues client notification; unknown contact still books',async()=>{const t=await setup();await t.req('/me','GET',null,'9003');await t.req('/v2/context','POST',{company_id:'nail'},'9003');const a=await t.book({manual:true,client_id:'9003'},'9002');assert.equal(a.status,201);assert.equal(a.data.user_id,'9003');assert.ok(t.DB.sqlite.prepare('SELECT text FROM outbox WHERE chat_id=? AND id LIKE ?').get('9003',a.data.id+':created:%'));const b=await t.book({manual:true,phone:'+79990000002'},'9002');assert.equal(b.status,201);assert.match(b.data.user_id,/^manual-/);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM outbox WHERE chat_id=?').get(b.data.user_id).n,0)});

test('no-show is distinct from completion and excluded from reviews, revenue and visits',async()=>{const t=await setup(),b=(await t.book()).data;assert.equal((await t.req('/bookings/'+b.id,'PATCH',{status:'confirmed'})).status,200);assert.equal((await t.req('/bookings/'+b.id,'PATCH',{status:'no_show'})).status,200);const records=(await t.req('/bookings?scope=company&company=nail')).data;assert.equal(records[0].visit_outcome,'no_show');const client=(await t.req('/v2/clients?company=nail')).data[0];assert.equal(client.visits,0);assert.equal(client.revenue,0);assert.equal(t.DB.sqlite.prepare("SELECT COUNT(*) n FROM outbox WHERE id LIKE ?").get(b.id+':review-request:%').n,0);await assert.rejects(createReview(t.DB,'9003',{booking_id:b.id,rating:5}),/состоявшегося/)});

test('normal completed historical booking can receive exactly one review',async()=>{const t=await setup(),b=(await t.book()).data;await t.req('/bookings/'+b.id,'PATCH',{status:'confirmed'});await t.req('/bookings/'+b.id,'PATCH',{status:'done'});t.DB.sqlite.prepare('UPDATE bookings SET starts_at=?,ends_at=? WHERE id=?').run(now()-7200,now()-3600,b.id);assert.equal((await t.req('/v7/reviews','POST',{booking_id:b.id,rating:5,text:'Excellent'},'9003')).status,201);assert.equal((await t.req('/v7/reviews','POST',{booking_id:b.id,rating:5},'9003')).status,409)});

test('bot first entry chooses language then documents; invite inherits owner language and persists tenant',async()=>{const t=await setup();await t.req('/v8/profile','POST',{language:'az',role:'specialist'});let msg=await botEntry(t.env,'https://example.com','9008');assert.ok(msg.reply_markup.inline_keyboard[0][0].callback_data.startsWith('entry:lang:'));msg=await botEntry(t.env,'https://example.com','9008',null,'entry:lang:ru');assert.ok(msg.reply_markup.inline_keyboard.at(-1)[0].callback_data.startsWith('entry:agree:'));const tenant={id:'nail',name:'Анна'};msg=await botEntry(t.env,'https://example.com','9003',tenant);assert.equal(t.DB.sqlite.prepare('SELECT language,theme FROM user_app_settings WHERE user_id=?').get('9003').language,'az');assert.equal(t.DB.sqlite.prepare('SELECT theme FROM user_app_settings WHERE user_id=?').get('9003').theme,'light');const accept=msg.reply_markup.inline_keyboard.at(-1)[0].callback_data;msg=await botEntry(t.env,'https://example.com','9003',null,accept);assert.match(msg.reply_markup.inline_keyboard[0][0].web_app.url,/company=nail/);assert.equal(t.DB.sqlite.prepare('SELECT company_id FROM client_links WHERE user_id=?').get('9003').company_id,'nail');msg=await botEntry(t.env,'https://example.com','9003');assert.match(msg.reply_markup.inline_keyboard[0][0].web_app.url,/company=nail/)});

test('document version change invalidates old acceptance and updates links safely',async()=>{const t=await setup();let msg=await botEntry(t.env,'https://example.com','9003');msg=await botEntry(t.env,'https://example.com','9003',null,'entry:lang:az');const accept=msg.reply_markup.inline_keyboard.at(-1)[0].callback_data;const d=(await config(t.DB)).documents;d.policy.version='release-10';d.policy.urls.az='https://example.com/policy-az';assert.equal((await t.set('documents',d)).status,200);await assert.rejects(botEntry(t.env,'https://example.com','9003',null,accept),/актуальные/);msg=await botEntry(t.env,'https://example.com','9003');assert.equal(msg.reply_markup.inline_keyboard[0][0].url,'https://example.com/policy-az');d.policy.urls.ru='javascript:alert(1)';assert.equal((await t.set('documents',d)).status,400)});

test('admin subscription extension, trial and pause preserve original business data',async()=>{const t=await setup();const a=await t.req('/companies/nail'),trial=a.data.subscription.trial_ends_at;assert.equal((await t.req('/v10/admin/specialist','POST',{company_id:'nail',action:'extend',days:30,confirm:true},'9001')).status,200);assert.equal((await t.req('/companies/nail')).data.subscription.status,'active');assert.equal(t.DB.sqlite.prepare('SELECT trial_ends_at FROM subscriptions WHERE company_id=?').get('nail').trial_ends_at,trial);assert.equal((await t.req('/v10/admin/specialist','POST',{company_id:'nail',action:'disable',confirm:true},'9001')).status,200);assert.equal((await t.book()).status,403);assert.equal((await t.req('/v10/admin/specialist','POST',{company_id:'nail',action:'restore',confirm:true},'9001')).status,200);assert.equal((await t.book()).status,201);assert.equal((await t.req('/companies/nail')).data.name,a.data.name)});

test('tariff price/trial settings apply to new subscriptions without resetting existing trial',async()=>{const t=await setup(),old=(await t.req('/companies/nail')).data.subscription;assert.equal((await t.set('tariff',{name:'Takt',description:'Booking',price:790,trial_days:10,enabled:true})).status,200);const s=(await t.req('/companies/nail')).data.subscription;assert.equal(s.price,790);assert.equal(s.trial_ends_at,old.trial_ends_at);const other=(await t.req('/companies/auto','GET',null,'9004')).data.subscription;assert.equal(other.trial_ends_at-other.trial_started_at,10*86400)});

test('feature flags support all, signed test users and off; cannot alter security features',async()=>{const t=await setup();const flags={reviews:{mode:'test',users:['9003']},help:{mode:'off',users:[]}};assert.equal((await t.set('flags',flags)).status,200);const c=await config(t.DB);assert.equal(enabled(c,'reviews','9003'),true);assert.equal(enabled(c,'reviews','9004'),false);assert.equal((await t.req('/v10/config','GET',null,'9004')).data.flags.reviews,false);assert.equal((await t.req('/v72/support','POST',{message:'Help me please'},'9003')).status,403);assert.equal((await t.set('BOT_TOKEN','unsafe')).status,400)});

test('broadcast preview sends nothing, confirmation queues once, unknown recipients rejected',async()=>{const t=await setup();for(const id of ['9002','9003','9004'])await t.req('/me','GET',null,id);const p=await t.req('/v10/admin/broadcast/preview','POST',{audience:'specialists',text:'Service update'},'9001');assert.equal(p.status,200);assert.equal(p.data.count,2);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM outbox').get().n,0);const data={id:p.data.id,token:p.data.token,confirm:true};assert.equal((await t.req('/v10/admin/broadcast/send','POST',{...data,confirm:false},'9001')).status,400);await Promise.all([t.req('/v10/admin/broadcast/send','POST',data,'9001'),t.req('/v10/admin/broadcast/send','POST',data,'9001')]);assert.equal(t.DB.sqlite.prepare("SELECT COUNT(*) n FROM outbox WHERE id LIKE 'broadcast:%'").get().n,2);assert.equal((await t.req('/v10/admin/broadcast/preview','POST',{audience:'selected',ids:['111'],text:'x'},'9001')).status,400)});

test('account blocking is main-admin-only and does not remove bookings or permit owner spoofing',async()=>{const t=await setup();await t.req('/me','GET',null,'9003');const b=(await t.book()).data;assert.equal((await t.req('/v10/admin/user','POST',{user_id:'9003',blocked:true,confirm:true},'9001')).status,200);assert.equal((await t.req('/bookings','GET',null,'9003')).status,403);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM bookings WHERE id=?').get(b.id).n,1);assert.equal((await t.req('/v10/admin/user','POST',{user_id:'9001',blocked:true,confirm:true},'9001')).status,400);await t.req('/v10/admin/user','POST',{user_id:'9003',blocked:false,confirm:true},'9001');assert.equal((await t.req('/bookings','GET',null,'9003')).status,200)});

test('known Telegram edit failure retries editing without sending another booking message',async()=>{const t=await setup(),b=(await t.book()).data;const original=fetch,calls=[];let mid=100;globalThis.fetch=async(u,o)=>{calls.push(u);return Response.json({ok:true,result:{message_id:mid++}})};try{await deliver(t.env);await t.req('/bookings/'+b.id,'PATCH',{status:'confirmed'});calls.length=0;globalThis.fetch=async(u,o)=>{calls.push(u);return Response.json({ok:false,error_code:429,parameters:{retry_after:60}})};await deliver(t.env);assert.ok(calls.some(u=>u.endsWith('/editMessageText')));assert.equal(calls.filter(u=>u.endsWith('/sendMessage')).length,0)}finally{globalThis.fetch=original}});

test('migration preserves historical data and preferences; new defaults use light theme',async()=>{const t=await setup();t.DB.sqlite.exec("INSERT INTO user_app_settings(user_id,language,theme,updated_at) VALUES('9009','az','dark',1)");await t.req('/me');assert.equal((await t.req('/v8/profile','GET',null,'9009')).data.theme,'dark');assert.equal((await t.req('/v8/profile','GET',null,'9010')).data.theme,'light');assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM services').get().n,9);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM schema_versions WHERE version=10').get().n,1)});

test('v9 to v10 migration leaves the existing 30-day booking horizon and data intact',async()=>{const t=await setup();t.DB.sqlite.exec("DELETE FROM schema_versions WHERE version=10; INSERT INTO schema_versions VALUES(9); INSERT INTO specialist_options(company_id,data) VALUES('nail','{\"horizon\":30}') ON CONFLICT(company_id) DO UPDATE SET data=excluded.data");const fresh={prepare:t.DB.prepare,batch:t.DB.batch};await ensureSchema(fresh);assert.equal(t.DB.sqlite.prepare("SELECT json_extract(data,'$.horizon') horizon FROM specialist_options WHERE company_id='nail'").get().horizon,30);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM services').get().n,9);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM schema_versions WHERE version=10').get().n,1)});

test('concurrent review submissions produce one review and a clear conflict',async()=>{const t=await setup(),b=(await t.book()).data;await t.req('/bookings/'+b.id,'PATCH',{status:'confirmed'});await t.req('/bookings/'+b.id,'PATCH',{status:'done'});t.DB.sqlite.prepare('UPDATE bookings SET starts_at=?,ends_at=? WHERE id=?').run(now()-7200,now()-3600,b.id);const responses=await Promise.all([t.req('/v7/reviews','POST',{booking_id:b.id,rating:5},'9003'),t.req('/v7/reviews','POST',{booking_id:b.id,rating:4},'9003')]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);assert.equal(t.DB.sqlite.prepare('SELECT COUNT(*) n FROM reviews WHERE booking_id=?').get(b.id).n,1)});

test('landing tariff follows administrator configuration instead of promising a stale price',async()=>{const {landing}=await import('../public/landing.js');const html=landing({trial_days:10,price:790,enabled:true},'az');assert.match(html,/10 gün — 0 ₽/);assert.match(html,/790 ₽ \/ ay/);assert.doesNotMatch(html,/590 ₽/);assert.doesNotMatch(landing({enabled:false}),/trial-offer/)});
