import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {database} from '../scripts/db.mjs';import worker from '../src/worker.js';import {ensureSchema} from '../src/v2.js';
import {clientInsights,setClientFlag,isBlockedClient,joinWaitlist,waitlistTick,rebookTick,addPhoto,portfolioLimit,saveTemplate,replyReview,exportCsv,winBack,checklist,PORTFOLIO_DEFAULT} from '../src/tools140.js';
const T=()=>Math.floor(Date.now()/1000),D=86400;let seq=0;
async function setup(){const DB=database();DB.sqlite.exec(fs.readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'));await ensureSchema(DB);return DB}
const svc=DB=>DB.sqlite.prepare("SELECT id,name FROM services WHERE company_id='nail' LIMIT 1").get();
function book(DB,user,startsDays,{status='confirmed',name='Анна',outcome}={}){const s=svc(DB),id='b'+(++seq)+'-'+Math.random().toString(36).slice(2,8),st=T()+Math.round(startsDays*D)+seq*7200;
 DB.sqlite.prepare('INSERT INTO bookings(id,company_id,service_id,user_id,name,phone,details,starts_at,ends_at,price,service_name,status,created_at,request_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'nail',s.id,user,name,'+79990000000','',st,st+3600,1000,s.name,status,T(),'rk-'+id);
 if(outcome)DB.sqlite.prepare('INSERT INTO booking_outcomes(booking_id,outcome,updated_at) VALUES(?,?,?)').run(id,outcome,T());return id}
test('14.2: клиенты — визиты, неявки, интервал и «давно не приходил»',async()=>{const DB=await setup();
 book(DB,'7001',-100);book(DB,'7001',-70);book(DB,'7001',-40);book(DB,'7002',-10,{outcome:'no_show'});book(DB,'7002',-5,{outcome:'no_show'});book(DB,'7003',-3);book(DB,'7003',5);
 const r=Object.fromEntries((await clientInsights(DB,'nail')).map(c=>[c.client_id,c]));
 assert.equal(r['7001'].visits,3);assert.equal(r['7001'].avg_interval_days,30);assert.equal(r['7001'].overdue,false);
 assert.equal(r['7002'].no_shows,2);assert.equal(r['7002'].visits,0);assert.equal(r['7003'].upcoming,1);
 book(DB,'7004',-200);book(DB,'7004',-170);const o=(await clientInsights(DB,'nail')).find(c=>c.client_id==='7004');assert.equal(o.overdue,true)});
test('14.2: чёрный список, теги и дни рождения — только для своих клиентов',async()=>{const DB=await setup();book(DB,'7001',-5);
 assert.equal((await setClientFlag(DB,'nail','9999',{blocked:true})).reason,'unknown');
 assert.equal((await setClientFlag(DB,'nail','7001',{blocked:true,tag:'VIP',birthday:'12-31'})).ok,true);assert.equal(await isBlockedClient(DB,'nail','7001'),true);
 assert.equal((await setClientFlag(DB,'nail','7001',{birthday:'31.12'})).reason,'birthday');assert.equal((await setClientFlag(DB,'nail','7001',{blocked:false})).ok,true);assert.equal(await isBlockedClient(DB,'nail','7001'),false);
 assert.equal((await clientInsights(DB,'nail'))[0].tag,'VIP')});
test('14.2: лист ожидания — вход, лимиты, одно уведомление при освобождении окна',async()=>{const DB=await setup();book(DB,'7001',-5);const s=svc(DB),day=new Date((T()+3*D)*1000).toISOString().slice(0,10);
 assert.equal((await joinWaitlist(DB,'7777',{company_id:'nail',service_id:s.id,date:day})).reason,'forbidden');
 const j=await joinWaitlist(DB,'7001',{company_id:'nail',service_id:s.id,date:day});assert.equal(j.ok,true);const j2=await joinWaitlist(DB,'7001',{company_id:'nail',service_id:s.id,date:day});assert.equal(j2.id,j.id);
 assert.equal((await joinWaitlist(DB,'7001',{company_id:'nail',service_id:s.id,date:'2020-01-01'})).reason,'date');
 let free=[];const deps={company:async()=>({id:'nail'}),enrichService:async x=>x,availableSlots:async()=>free};
 assert.equal((await waitlistTick({APP_URL:'https://x'},DB,deps)).sent,0);free=[1];
 assert.equal((await waitlistTick({APP_URL:'https://x'},DB,deps)).sent,1);assert.equal((await waitlistTick({APP_URL:'https://x'},DB,deps)).sent,0);
 const row=DB.sqlite.prepare("SELECT id,chat_id,text FROM outbox WHERE id LIKE 'waitlist:%'").get();assert.equal(row.chat_id,'7001');assert.match(JSON.parse(row.text).text,/Освободилось время/);
 assert.equal(DB.sqlite.prepare('SELECT status FROM waitlist').get().status,'notified')});
test('14.2: «пора записаться снова» — один раз на последний визит',async()=>{const DB=await setup();const bk=(DB,u,d)=>book(DB,u,d,{status:'done'});bk(DB,'7001',-100);bk(DB,'7001',-70);bk(DB,'7001',-40);
 assert.equal((await rebookTick({APP_URL:'https://x'},DB)).sent,1);assert.equal((await rebookTick({APP_URL:'https://x'},DB)).sent,0);
 assert.match(JSON.parse(DB.sqlite.prepare("SELECT text FROM outbox WHERE id LIKE 'rebook:%'").get().text).text,/Пора записаться снова/);
 bk(DB,'7002',-100);bk(DB,'7002',-70);bk(DB,'7002',-40);book(DB,'7002',3);assert.equal((await rebookTick({APP_URL:'https://x'},DB)).sent,0)});
test('14.2: портфолио — формат, лимит 20 по умолчанию, до 30 по настройке',async()=>{const DB=await setup();const ok='data:image/jpeg;base64,'+'A'.repeat(100);
 assert.equal((await addPhoto(DB,'nail','data:image/png;base64,AAA')).reason,'format');assert.equal((await addPhoto(DB,'nail','data:image/jpeg;base64,'+'A'.repeat(150001))).reason,'format');
 for(let i=0;i<PORTFOLIO_DEFAULT;i++)assert.equal((await addPhoto(DB,'nail',ok)).ok,true);assert.equal((await addPhoto(DB,'nail',ok)).reason,'limit');
 DB.sqlite.prepare("INSERT INTO service_config(key,value,updated_at,updated_by) VALUES('portfolio_limit','99',1,'t')").run();assert.equal(await portfolioLimit(DB),30);assert.equal((await addPhoto(DB,'nail',ok)).ok,true)});
test('14.2: шаблоны, ответ на отзыв, экспорт без CSV-инъекций, чеклист',async()=>{const DB=await setup();const b=book(DB,'7001',-5);
 assert.equal((await saveTemplate(DB,'nail',{title:'',text:'x'})).reason,'empty');const t=await saveTemplate(DB,'nail',{title:'Напоминание',text:'Ждём вас!'});assert.equal(t.ok,true);assert.equal((await saveTemplate(DB,'nail',{id:t.id,title:'Новое',text:'Текст'})).ok,true);
 for(let i=0;i<19;i++)await saveTemplate(DB,'nail',{title:'t'+i,text:'x'});assert.equal((await saveTemplate(DB,'nail',{title:'ещё',text:'x'})).reason,'limit');
 assert.equal((await replyReview(DB,'nail',b,'Спасибо')).reason,'missing');DB.sqlite.prepare("INSERT INTO reviews(booking_id,company_id,user_id,client_name,service_name,rating,text,created_at) VALUES(?,?,?,?,?,?,?,?)").run(b,'nail','7001','Анна','Маникюр',5,'Супер',T());
 assert.equal((await replyReview(DB,'nail',b,'Спасибо!')).ok,true);assert.equal(DB.sqlite.prepare('SELECT text FROM review_replies').get().text,'Спасибо!');
 book(DB,'7005',-9,{name:'=HYPERLINK("x")'});const csv=(await exportCsv(DB,'nail','clients')).csv;assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.includes("'=HYPERLINK"));assert.ok(!/^=/m.test(csv));
 const c=await checklist(DB,'nail');assert.equal(c.total,4);assert.ok(c.items.find(i=>i.key==='booking').done)});
test('14.2: «вернуть клиента» — лимит раз в неделю, только достижимым и не из чёрного списка',async()=>{const DB=await setup();book(DB,'7001',-90);book(DB,'manual-nail-123',-90);
 assert.equal((await winBack({},DB,'nail','manual-nail-123','Привет')).reason,'unreachable');
 assert.equal((await winBack({},DB,'nail','7001','Скучаем! Скидка 10%')).ok,true);assert.equal((await winBack({},DB,'nail','7001','Ещё раз')).reason,'recent');
 await setClientFlag(DB,'nail','7001',{blocked:true});DB.sqlite.exec("DELETE FROM outbox");assert.equal((await winBack({},DB,'nail','7001','Привет')).reason,'blocked')});
test('14.2: API инструментов — права, список и действие',async()=>{const DB=await setup();book(DB,'7001',-5);const env={DB,DEV_MODE:'true',SUPERADMIN_IDS:'9001',ADMIN_ID:'9001'};
 const call=(role,path,body)=>worker.fetch(new Request('http://localhost'+path,{method:body?'POST':'GET',headers:{'x-demo-role':role,'content-type':'application/json'},body:body?JSON.stringify(body):undefined}),env);
 assert.equal((await call('client','/api/v140/tools?company=nail')).status,403);
 const r=await call('owner','/api/v140/tools?company=nail');assert.ok([200,403].includes(r.status));
 assert.equal((await call('client','/api/v140/tools/action',{company:'nail',action:'client_flag',client_id:'7001',blocked:true})).status,403);
 assert.equal((await call('client','/api/v140/portfolio?company=nail')).status,403)});
test('14.2: миграция аддитивная',()=>{const m=fs.readFileSync('migrations/0015_takt_v142.sql','utf8');assert.ok(!/DROP|DELETE|ALTER/i.test(m));assert.ok(!/CREATE TABLE(?! IF NOT EXISTS)/.test(m))});
