-- Takt 11: additive Control Center tables and compatible scheduling guards.
DROP TRIGGER IF EXISTS blocked_insert_guard;
CREATE TRIGGER blocked_insert_guard BEFORE INSERT ON blocked_slots WHEN EXISTS(SELECT 1 FROM blocked_slots WHERE company_id=NEW.company_id AND starts_at<NEW.ends_at AND ends_at>NEW.starts_at) BEGIN SELECT RAISE(ABORT,'SLOT_TAKEN'); END;
DROP TRIGGER IF EXISTS booking_update_guard;
CREATE TRIGGER booking_update_guard BEFORE UPDATE OF starts_at,ends_at,status ON bookings WHEN NEW.status IN ('pending','confirmed') AND (EXISTS(SELECT 1 FROM bookings WHERE company_id=NEW.company_id AND id<>NEW.id AND status IN ('pending','confirmed') AND starts_at<NEW.ends_at AND ends_at>NEW.starts_at) OR ((NEW.starts_at<>OLD.starts_at OR NEW.ends_at<>OLD.ends_at OR OLD.status NOT IN ('pending','confirmed')) AND EXISTS(SELECT 1 FROM blocked_slots WHERE company_id=NEW.company_id AND starts_at<NEW.ends_at AND ends_at>NEW.starts_at))) BEGIN SELECT RAISE(ABORT,'SLOT_TAKEN'); END;
CREATE TABLE IF NOT EXISTS paid_terms(company_id TEXT PRIMARY KEY REFERENCES companies(id),value TEXT NOT NULL,effective_until INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tariff_catalog(id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,period_days INTEGER NOT NULL,trial_days INTEGER NOT NULL,description TEXT NOT NULL,active INTEGER NOT NULL,limits TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS booking_plan_limit BEFORE INSERT ON bookings WHEN COALESCE((SELECT json_extract(value,'$.limits.bookings_month') FROM paid_terms WHERE company_id=NEW.company_id AND effective_until>unixepoch()),(SELECT json_extract(value,'$.limits.bookings_month') FROM service_config WHERE key='tariff'),0)>0 AND (SELECT COUNT(*) FROM bookings WHERE company_id=NEW.company_id AND strftime('%Y-%m',created_at,'unixepoch')=strftime('%Y-%m',NEW.created_at,'unixepoch'))>=COALESCE((SELECT json_extract(value,'$.limits.bookings_month') FROM paid_terms WHERE company_id=NEW.company_id AND effective_until>unixepoch()),(SELECT json_extract(value,'$.limits.bookings_month') FROM service_config WHERE key='tariff'),0) AND NOT EXISTS(SELECT 1 FROM bookings WHERE company_id=NEW.company_id AND user_id=NEW.user_id AND request_key=NEW.request_key) BEGIN SELECT RAISE(ABORT,'PLAN_LIMIT'); END;
CREATE TABLE IF NOT EXISTS admin_operation_receipts(id TEXT PRIMARY KEY,actor TEXT NOT NULL,fingerprint TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_roles(user_id TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('SUPPORT','FINANCE','CONTENT')),active INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS subscription_freezes(company_id TEXT PRIMARY KEY REFERENCES companies(id),started_at INTEGER NOT NULL,remaining_paid INTEGER NOT NULL,remaining_trial INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS promos(code TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('percent','amount')),value INTEGER NOT NULL,expires_at INTEGER NOT NULL,max_uses INTEGER NOT NULL,per_user INTEGER NOT NULL DEFAULT 1,new_only INTEGER NOT NULL DEFAULT 0,tariff TEXT NOT NULL DEFAULT 'Takt',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS promo_uses(id TEXT PRIMARY KEY,code TEXT NOT NULL REFERENCES promos(code),company_id TEXT NOT NULL REFERENCES companies(id),user_id TEXT NOT NULL,discount INTEGER NOT NULL,price INTEGER NOT NULL,created_at INTEGER NOT NULL,UNIQUE(id));
CREATE TABLE IF NOT EXISTS content_faq(id TEXT PRIMARY KEY,category TEXT NOT NULL,question TEXT NOT NULL,answer TEXT NOT NULL,language TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS content_translations(key TEXT NOT NULL,language TEXT NOT NULL,value TEXT NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(key,language));
CREATE TABLE IF NOT EXISTS funnel_counts(company_id TEXT NOT NULL,day TEXT NOT NULL,stage TEXT NOT NULL,n INTEGER NOT NULL,PRIMARY KEY(company_id,day,stage));
CREATE TABLE IF NOT EXISTS funnel_seen(user_id TEXT NOT NULL,company_id TEXT NOT NULL,day TEXT NOT NULL,stage TEXT NOT NULL,PRIMARY KEY(user_id,company_id,day,stage));
CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY);
INSERT OR IGNORE INTO schema_versions VALUES(11);
