import http from 'node:http';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {database} from './db.mjs';
import worker from '../src/worker.js';
mkdirSync('.local',{recursive:true});const dbPath=process.env.TAKT_TEST_DB||'.local/takt.sqlite';const first=!existsSync(dbPath);const db=database(dbPath);
if(first)db.sqlite.exec(readFileSync('migrations/0001_initial.sql','utf8'));
db.sqlite.exec("INSERT OR IGNORE INTO memberships VALUES('nail','9002')");
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml'};
const env={DB:db,DEV_MODE:'true',SUPERADMIN_IDS:'9001',ASSETS:{fetch(req){let path=new URL(req.url).pathname;const base=resolve('public'),file=resolve(base,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(base+'/'))return new Response('Not found',{status:404});try{return new Response(readFileSync(file),{headers:{'Content-Type':mime[extname(file)]||'application/octet-stream'}})}catch{return new Response('Not found',{status:404})}}}};
http.createServer(async(req,res)=>{try{const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>140000){res.writeHead(413);res.end();return}chunks.push(chunk)}const request=new Request('http://127.0.0.1:8787'+req.url,{method:req.method,headers:req.headers,...(['GET','HEAD'].includes(req.method)?{}:{body:Buffer.concat(chunks)})});const response=await worker.fetch(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch{res.writeHead(500);res.end('Local server error')}}).listen(8787,'127.0.0.1',()=>console.log('Такт: http://127.0.0.1:8787 · only local demo authentication'));
