import {entityTranslations} from './content12.js';
import {config,legalVersions,LANGS,customText,isMainAdmin,enforceAccount} from './v10.js';
import {legalDoc} from '../public/i18n.js';
const now=()=>Math.floor(Date.now()/1000);
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const labels={ru:['Выберите язык','Ознакомьтесь с документами','Продолжая, вы принимаете обязательные документы Takt.','Принимаю документы','Открыть Takt','Записаться','Добро пожаловать в Takt — ваш личный сервис онлайн-записи.','Запись к','Как это работает?','Поддержка'],kk:['Тілді таңдаңыз','Құжаттармен танысыңыз','Жалғастыру арқылы Takt міндетті құжаттарын қабылдайсыз.','Құжаттарды қабылдаймын','Takt ашу','Жазылу','Takt-қа қош келдіңіз — жеке онлайн жазылу сервисіңіз.','Жазылу','Қалай жұмыс істейді?','Қолдау'],az:['Dili seçin','Sənədlərlə tanış olun','Davam etməklə Takt-ın məcburi sənədlərini qəbul edirsiniz.','Sənədləri qəbul edirəm','Takt-ı aç','Qeyd ol','Takt-a xoş gəlmisiniz — şəxsi onlayn qeyd xidmətiniz.','Qeyd üçün','Necə işləyir?','Dəstək'],uz:['Tilni tanlang','Hujjatlar bilan tanishing','Davom etib, Takt majburiy hujjatlarini qabul qilasiz.','Hujjatlarni qabul qilaman','Taktni ochish','Yozilish','Taktga xush kelibsiz — shaxsiy onlayn yozuv xizmatingiz.','Yozilish','Qanday ishlaydi?','Yordam']};
const Q={ru:{h24:'Ближайшие 24 часа',first:'первая в',wait:'Ждут подтверждения',cal:'📅 Расписание',cli:'👥 Клиенты',mine:'📋 Мои записи',next:'Ближайшая запись'},kk:{h24:'Алдағы 24 сағат',first:'біріншісі',wait:'Растауды күтуде',cal:'📅 Кесте',cli:'👥 Клиенттер',mine:'📋 Менің жазылуларым',next:'Жақын жазылу'},az:{h24:'Növbəti 24 saat',first:'birincisi',wait:'Təsdiq gözləyir',cal:'📅 Cədvəl',cli:'👥 Müştərilər',mine:'📋 Qeydlərim',next:'Ən yaxın qeyd'},uz:{h24:'Keyingi 24 soat',first:'birinchisi',wait:'Tasdiq kutmoqda',cal:'📅 Jadval',cli:'👥 Mijozlar',mine:'📋 Yozuvlarim',next:'Eng yaqin yozuv'}};
const LOC={ru:'ru-RU',kk:'kk-KZ',az:'az-AZ',uz:'uz-UZ'};
const stamp=(ts,tz,lang,withDate)=>{const d=new Date(ts*1000),loc=LOC[lang]||LOC.ru,f=z=>(withDate?new Intl.DateTimeFormat(loc,{timeZone:z,day:'numeric',month:'long'}).format(d)+', ':'')+new Intl.DateTimeFormat(loc,{timeZone:z,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d);try{return f(tz)}catch{return f('UTC')}};
const tzOf=async(db,companyId)=>{try{const r=await db.prepare('SELECT data FROM specialist_options WHERE company_id=?').bind(companyId).first();return JSON.parse(r?.data||'{}').timezone||'Asia/Almaty'}catch{return 'Asia/Almaty'}};
// Короткая сводка в приветствии: специалисту — ближайшие 24 часа, клиенту — его ближайшая запись. Любая ошибка не должна ломать приветствие.
async function glance(db,id,tenant,lang){const Lq=Q[lang]||Q.ru,t=now();try{
 if(tenant){const b=await db.prepare("SELECT starts_at,service_name FROM bookings WHERE company_id=? AND user_id=? AND status IN ('pending','confirmed') AND starts_at>? ORDER BY starts_at LIMIT 1").bind(tenant.id,id,t).first();if(!b)return null;const tz=await tzOf(db,tenant.id);return {text:`${Lq.next}: <b>${stamp(b.starts_at,tz,lang,true)}</b>${b.service_name?' · '+esc(b.service_name):''}`,row:[{text:Lq.mine,web_app:{url:null,params:{view:'my'}}}]}}
 const m=await db.prepare('SELECT company_id FROM memberships WHERE user_id=? ORDER BY rowid LIMIT 1').bind(id).first();if(!m)return null;const tz=await tzOf(db,m.company_id);
 const a=await db.prepare("SELECT COUNT(*) n,MIN(starts_at) first FROM bookings WHERE company_id=? AND status IN ('pending','confirmed') AND starts_at BETWEEN ? AND ?").bind(m.company_id,t,t+86400).first(),w=await db.prepare("SELECT COUNT(*) n FROM bookings WHERE company_id=? AND status='pending' AND starts_at>?").bind(m.company_id,t).first();
 const lines=[];if(a?.n)lines.push(`${Lq.h24}: <b>${a.n}</b> · ${Lq.first} <b>${stamp(a.first,tz,lang,false)}</b>`);if(w?.n)lines.push(`${Lq.wait}: <b>${w.n}</b>`);
 return {text:lines.join('\n'),row:[{text:Lq.cal,web_app:{url:null,params:{view:'calendar'}}},{text:Lq.cli,web_app:{url:null,params:{view:'clients'}}}]}
}catch{return null}}
const languageLabels={ru:'🇷🇺 Русский',kk:'🇰🇿 Қазақша',az:'🇦🇿 Azərbaycan dili',uz:'🇺🇿 O‘zbekcha'};
const getVersion=async versions=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(versions)))),x=>x.toString(16).padStart(2,'0')).join('').slice(0,10);
export async function botEntry(env,origin,id,invited=null,callback=null){const db=env.DB;await enforceAccount(db,id);const cfg=await config(db),versions=await legalVersions(db);
 let entry=await db.prepare('SELECT * FROM bot_entry WHERE user_id=?').bind(id).first(),prefs=await db.prepare('SELECT * FROM user_app_settings WHERE user_id=?').bind(id).first();
 if(invited){entry={company_id:invited.id};const owner=await db.prepare('SELECT s.language FROM memberships m LEFT JOIN user_app_settings s ON s.user_id=m.user_id WHERE m.company_id=? ORDER BY m.rowid LIMIT 1').bind(invited.id).first();const language=LANGS.includes(owner?.language)?owner.language:'ru';await db.prepare("INSERT INTO user_app_settings(user_id,language,role,theme,updated_at) VALUES(?,?,?,'light',?) ON CONFLICT(user_id) DO UPDATE SET language=excluded.language,updated_at=excluded.updated_at").bind(id,language,'client',now()).run();prefs=await db.prepare('SELECT * FROM user_app_settings WHERE user_id=?').bind(id).first()}
 else if(!entry?.company_id&&!await db.prepare('SELECT 1 FROM memberships WHERE user_id=?').bind(id).first()){const link=await db.prepare('SELECT company_id FROM client_links WHERE user_id=? ORDER BY last_seen DESC LIMIT 1').bind(id).first();if(link)entry={company_id:link.company_id}}
 await db.prepare('INSERT INTO bot_entry VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET company_id=excluded.company_id,updated_at=excluded.updated_at').bind(id,entry?.company_id||null,now()).run();
 const tenant=entry?.company_id?await db.prepare('SELECT id,name FROM companies WHERE id=? AND active=1').bind(entry.company_id).first():null;
 if(callback?.startsWith('entry:lang:')){const lang=callback.slice(11);if(!cfg.languages.includes(lang))throw Object.assign(new Error('Выберите доступный язык'),{status:400});await db.prepare("INSERT INTO user_app_settings(user_id,language,role,theme,updated_at) VALUES(?,?,?,'light',?) ON CONFLICT(user_id) DO UPDATE SET language=excluded.language,role=CASE WHEN user_app_settings.role='' THEN excluded.role ELSE user_app_settings.role END,updated_at=excluded.updated_at").bind(id,lang,tenant?'client':'specialist',now()).run();prefs=await db.prepare('SELECT * FROM user_app_settings WHERE user_id=?').bind(id).first()}
 const lang=prefs?.language||'ru',L=labels[lang]||labels.ru;if(tenant){const tr=await entityTranslations(db,'company',tenant.id);tenant.name=tr[lang]?.name||tenant.name}
 const base=new URL(env.APP_URL||origin);if(tenant)base.searchParams.set('company',tenant.id);
 const app=(params={})=>{const u=new URL(base);for(const [k,v] of Object.entries(params))u.searchParams.set(k,v);return u.href};
 if(callback?.startsWith('entry:agree:')){if(!prefs?.language||callback.slice(12)!==await getVersion(versions))throw Object.assign(new Error('Откройте актуальные документы'),{status:409});await db.batch([db.prepare("UPDATE user_app_settings SET policy_version=?,consent_version=?,terms_version=?,consent_at=?,updated_at=?,role=CASE WHEN role='' THEN ? ELSE role END WHERE user_id=?").bind(versions.policy,versions.consent,versions.terms,now(),now(),tenant?'client':'specialist',id),...(tenant?[db.prepare('INSERT INTO client_links VALUES(?,?,?,?) ON CONFLICT(user_id,company_id) DO UPDATE SET last_seen=excluded.last_seen').bind(id,tenant.id,now(),Date.now())]:[])]);prefs=await db.prepare('SELECT * FROM user_app_settings WHERE user_id=?').bind(id).first()}
 let text,keyboard;
 if(!prefs?.language){text='<b>'+L[0]+'</b>';keyboard=cfg.languages.map(l=>[{text:languageLabels[l],callback_data:'entry:lang:'+l}])}
 else if(prefs.policy_version!==versions.policy||prefs.consent_version!==versions.consent||prefs.terms_version!==versions.terms){text=`<b>${L[1]}</b>\n\n${L[2]}`;keyboard=['policy','consent','terms'].map(k=>[{text:legalDoc(k,lang)[0],url:cfg.documents[k]?.urls?.[lang]||new URL('/documents?type='+k+'&lang='+lang,base).href}]);keyboard.push([{text:L[3],style:'success',callback_data:'entry:agree:'+await getVersion(versions)}])}
 else{const greeting=tenant?customText(cfg,'welcome_client',lang,`${L[7]} ${tenant.name}`):customText(cfg,'welcome_specialist',lang,L[6]);const g=await glance(db,id,tenant,lang);text='<b>'+esc(greeting)+'</b>'+(g?.text?'\n\n'+g.text:'');keyboard=[[{text:tenant?L[5]:L[4],style:'primary',web_app:{url:app()}}],...(g?[g.row.map(b=>({text:b.text,web_app:{url:app(b.web_app.params)}}))]:[]),[{text:L[8],style:'success',web_app:{url:app({guide:'1'})}},{text:L[9],style:'danger',web_app:{url:app({support:'1'})}}]];if(isMainAdmin(env,id))keyboard.push([{text:'Админ-панель',web_app:{url:app({view:'admin'})}}])}
 return {text,parse_mode:'HTML',reply_markup:{inline_keyboard:keyboard}};
}
