import {localDate,localMinute,fromLocal,dateShift,messagePayload,when,escHtml} from './v3.js';
const now=()=>Math.floor(Date.now()/1000);
// A crashed/ambiguous send is deliberately NOT automatically retried: Telegram has no idempotency key.
export async function deliverMessages(env,{ensureSchema,company,enrichCompany,queue}){
 if(!env.BOT_TOKEN||!env.DB)return;const db=env.DB;await ensureSchema(db);
 const cache=new Map(),getCompany=async id=>{if(!cache.has(id))cache.set(id,await company(db,id));return cache.get(id)};
 const due=(await db.prepare(`SELECT b.* FROM bookings b WHERE b.status IN ('pending','confirmed') AND b.starts_at>? AND b.starts_at<=? AND ((b.user_id NOT LIKE 'manual-%' AND COALESCE((SELECT json_extract(data,'$.notifications.reminders') FROM specialist_options WHERE company_id=b.company_id),1)=1 AND NOT EXISTS(SELECT 1 FROM outbox o WHERE o.id=b.id||':reminder:'||b.starts_at)) OR (b.starts_at<=? AND COALESCE((SELECT json_extract(data,'$.notifications.master_reminder') FROM specialist_options WHERE company_id=b.company_id),0)=1 AND EXISTS(SELECT 1 FROM memberships m WHERE m.company_id=b.company_id AND NOT EXISTS(SELECT 1 FROM outbox o WHERE o.id=b.id||':master-reminder:'||b.starts_at||':'||m.user_id)))) ORDER BY b.starts_at LIMIT 12`).bind(now(),now()+86400,now()+3600).all()).results;
 for(const b of due){const c=await getCompany(b.company_id);if(c.notifications.reminders&&/^\d+$/.test(b.user_id))await queue(db,`${b.id}:reminder:${b.starts_at}`,b.user_id,JSON.stringify(messagePayload(b,c,'reminder'))).run();if(c.notifications.master_reminder&&b.starts_at<=now()+3600){const members=(await db.prepare('SELECT user_id FROM memberships WHERE company_id=?').bind(c.id).all()).results;for(const m of members)await queue(db,`${b.id}:master-reminder:${b.starts_at}:${m.user_id}`,m.user_id,JSON.stringify(messagePayload(b,c,'master_reminder',true))).run()}}
 const summaries=(await db.prepare(`SELECT c.* FROM companies c JOIN specialist_options o ON o.company_id=c.id WHERE c.active=1 AND json_extract(o.data,'$.notifications.summary')=1 ORDER BY c.id`).all()).results;
 for(const raw of summaries){const c=await getCompany(raw.id),minute=localMinute(now(),c.timezone);if(minute<480||minute>=540)continue;const d=localDate(now(),c.timezone),start=fromLocal(d,0,c.timezone),end=fromLocal(dateShift(d,1),0,c.timezone);const members=(await db.prepare(`SELECT m.user_id FROM memberships m WHERE m.company_id=? AND NOT EXISTS(SELECT 1 FROM outbox WHERE id=?||m.user_id)`).bind(c.id,`summary:${c.id}:${d}:`).all()).results;if(!members.length)continue;
 const stats=await db.prepare(`SELECT COUNT(*) n,MIN(starts_at) first,MAX(starts_at) last FROM bookings WHERE company_id=? AND status IN ('pending','confirmed','done') AND starts_at>=? AND starts_at<?`).bind(c.id,start,end).first();const message=`☀️ <b>Доброе утро</b>\n\nСегодня у вас записей: <b>${stats.n}</b>.${stats.n?`\nПервая — <b>${when(stats.first,c.timezone).time}</b>\nПоследняя — <b>${when(stats.last,c.timezone).time}</b>`:'\nСегодня свободный день.'}`;for(const m of members)await queue(db,`summary:${c.id}:${d}:${m.user_id}`,m.user_id,JSON.stringify({text:message,parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'Открыть расписание',web_app:{url:(env.APP_URL||'https://takt.teymurstudent.workers.dev')+'/?view=calendar'}}]]}})).run();}
 const rows=(await db.prepare('SELECT * FROM outbox WHERE sent_at IS NULL AND attempts<5 AND lease_until<? ORDER BY created_at,id LIMIT 12').bind(now()).all()).results;
 for(const row of rows){let payload={text:row.text};try{const p=JSON.parse(row.text);if(p.text)payload=p}catch{}
 const meta=payload.takt;delete payload.takt;
 if(meta){const b=await db.prepare('SELECT * FROM bookings WHERE id=?').bind(meta.booking).first();const reminder=['reminder','master_reminder'].includes(meta.event);let stale=!b||(['created','confirmed','moved','reminder','master_reminder'].includes(meta.event)&&(b.starts_at!==meta.start||b.status==='cancelled'))||reminder&&(!['pending','confirmed'].includes(b.status)||b.starts_at<=now());if(!stale){const c=await getCompany(b.company_id);stale=meta.event==='reminder'&&!c.notifications.reminders||meta.admin&&c.notifications[meta.event]===false;if(!stale){const make=(action='')=>{const u=new URL(env.APP_URL||'https://takt.teymurstudent.workers.dev');if(!meta.admin)u.searchParams.set('company',b.company_id);u.searchParams.set('booking',b.id);if(action)u.searchParams.set('action',action);return u.href};payload.reply_markup={inline_keyboard:[[{text:meta.admin?'Открыть запись':'Моя запись',web_app:{url:make()}}]]};if(meta.event==='reminder'&&b.starts_at>now()+c.cancel_hours*3600)payload.reply_markup.inline_keyboard.push([...(c.allow_reschedule?[{text:'Перенести',web_app:{url:make('move')}}]:[]),{text:'Отменить',web_app:{url:make('cancel')}}]);}}
 if(stale){await db.prepare('UPDATE outbox SET sent_at=? WHERE id=? AND sent_at IS NULL').bind(now(),row.id).run();continue}}
 // Commit a non-retryable claim BEFORE network I/O. Another isolate cannot send it again.
 const claim=await db.prepare('UPDATE outbox SET attempts=5,lease_until=? WHERE id=? AND sent_at IS NULL AND attempts<5 AND lease_until<? RETURNING id').bind(now()+300,row.id,now()).first();if(!claim)continue;
 const record=state=>db.prepare('INSERT INTO delivery_state(id,state,updated_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,updated_at=excluded.updated_at').bind(row.id,state,now()).run();await record('sending');
 try{const res=await fetch(`https://api.telegram.org/bot${env.BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:row.chat_id,...payload}),signal:AbortSignal.timeout(10000)}),data=await res.json();if(data.ok){await db.prepare('UPDATE outbox SET sent_at=? WHERE id=?').bind(now(),row.id).run();await record('sent')}else if(data.error_code===429||data.error_code>=500){const attempts=row.attempts+1;await db.prepare('UPDATE outbox SET attempts=?,lease_until=? WHERE id=?').bind(attempts,now()+Math.max(60,Math.min(86400,Number(data.parameters?.retry_after)||300)),row.id).run();await record(attempts>=5?'failed':'retry')}else await record(data.error_code===403?'blocked':'failed')}
 catch{await record('unknown')}
 }
}
