import {requireLegacyAdmin,adminRole} from './control-auth.js';
// Additive operational controls. Authentication remains Telegram initData on every request.
export const schema10=[
`CREATE TABLE IF NOT EXISTS service_config(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at INTEGER NOT NULL,updated_by TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS admin_audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,before_value TEXT NOT NULL,after_value TEXT NOT NULL,created_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS account_controls(user_id TEXT PRIMARY KEY,blocked INTEGER NOT NULL DEFAULT 0 CHECK(blocked IN (0,1)),updated_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS specialist_controls(company_id TEXT PRIMARY KEY REFERENCES companies(id),disabled INTEGER NOT NULL DEFAULT 0 CHECK(disabled IN (0,1)),updated_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS bot_entry(user_id TEXT PRIMARY KEY,company_id TEXT,updated_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS booking_outcomes(booking_id TEXT PRIMARY KEY REFERENCES bookings(id),outcome TEXT NOT NULL CHECK(outcome IN ('done','no_show')),updated_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS admin_broadcasts(id TEXT PRIMARY KEY,actor TEXT NOT NULL,text TEXT NOT NULL,recipients TEXT NOT NULL,token TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'preview',created_at INTEGER NOT NULL,sent_at INTEGER)`,
`CREATE TABLE IF NOT EXISTS api_limits(user_id TEXT NOT NULL,window INTEGER NOT NULL,n INTEGER NOT NULL,PRIMARY KEY(user_id,window))`,
`CREATE TABLE IF NOT EXISTS booking_message_delivery(booking_id TEXT NOT NULL,chat_id TEXT NOT NULL,lease_until INTEGER NOT NULL DEFAULT 0,uncertain INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(booking_id,chat_id))`,
`CREATE INDEX IF NOT EXISTS admin_audit_time ON admin_audit(created_at DESC)`
];
const stamp=()=>Math.floor(Date.now()/1000);
const error=(status,message)=>{throw Object.assign(new Error(message),{status})};
export const LANGS=['ru','kk','az','uz'];
export const defaults={cancel_hours:24,tariff:{name:'Takt',description:'Ваш личный сервис онлайн-записи',price:590,trial_days:7,enabled:true,period_days:30,limits:{services:0,bookings_month:0}},support:'',languages:LANGS,documents:{policy:{version:'2026-10-05-v2',urls:{}},consent:{version:'2026-10-05-v2',urls:{}},terms:{version:'2026-10-05-v2',urls:{}}},texts:{},flags:{reviews:{mode:'all',users:[]},help:{mode:'all',users:[]}},notification_intervals:{client_24h:24,client_2h:2,master_2h:2,master_reminder_minutes:60,retry_seconds:300},announcement:{enabled:false,text:'',language:'ru',audience:'all',starts_at:0,ends_at:0}};
export const mainAdmin=env=>String(env.ADMIN_ID||env.SUPERADMIN_IDS?.split(',')[0]||'').trim();
export const isMainAdmin=(env,id)=>!!mainAdmin(env)&&mainAdmin(env)===String(id);
export async function config(db){const c=structuredClone(defaults);for(const r of (await db.prepare('SELECT key,value FROM service_config').all()).results){if(r.key in c)try{c[r.key]=JSON.parse(r.value)}catch{}}return c}
export async function legalVersions(db){const c=await config(db);return Object.fromEntries(Object.entries(c.documents).map(([k,v])=>[k,v.version]))}
export function enabled(c,key,id,companyId){const f=c.flags[key];if(!f)return true;if(f.mode==='all')return true;if(f.mode==='specialists')return !!companyId&&f.companies.includes(companyId);if(f.mode==='test')return f.users.includes(String(id));if(f.mode==='percent'){let hash=0;for(const x of String(id))hash=(hash*31+x.charCodeAt(0))>>>0;return !!id&&hash%100<f.percent}return false}
export function customText(c,key,lang,fallback){return c.texts[key]?.[lang]||fallback}
function clean(v,max){return typeof v==='string'?v.trim().slice(0,max):''}
function https(v){if(!v)return '';try{const u=new URL(v);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href}catch{}error(400,'Нужна безопасная HTTPS-ссылка')}
export function validateConfig(key,v){
 if(key==='cancel_hours'){if(!Number.isInteger(v)||v<0||v>168)error(400,'От 0 до 168 часов');return v}
 if(key==='tariff'){if(!v||!Number.isInteger(v.price)||v.price<0||v.price>100000||!Number.isInteger(v.trial_days)||v.trial_days<0||v.trial_days>90||typeof v.enabled!=='boolean'||!clean(v.name,60))error(400,'Проверьте параметры тарифа');const period=v.period_days??30,limits=v.limits||{services:0,bookings_month:0};if(!Number.isInteger(period)||period<1||period>366||['services','bookings_month'].some(k=>!Number.isInteger(limits[k])||limits[k]<0||limits[k]>100000))error(400,'Проверьте период и лимиты');return {name:clean(v.name,60),description:clean(v.description,300),price:v.price,trial_days:v.trial_days,enabled:v.enabled,period_days:period,limits}}
 if(key==='support'){const s=clean(v,32).replace(/^@/,'');if(s&&!/^[a-zA-Z][a-zA-Z0-9_]{4,31}$/.test(s))error(400,'Укажите Telegram username поддержки');return s}
 if(key==='languages'){if(!Array.isArray(v)||!v.length||!v.includes('ru')||v.some(x=>!LANGS.includes(x)))error(400,'Русский должен оставаться доступен');return [...new Set(v)]}
 if(key==='documents'){const out={};for(const k of ['policy','consent','terms']){const d=v?.[k];if(!d||!/^[-a-zA-Z0-9._]{1,60}$/.test(d.version||''))error(400,'Укажите версию каждого документа');const urls={};for(const l of LANGS)if(d.urls?.[l])urls[l]=https(clean(d.urls[l],500));out[k]={version:d.version,urls}}return out}
 if(key==='texts'){const out={};for(const [k,translations] of Object.entries(v||{})){if(!['welcome_specialist','welcome_client','created','confirmed','cancelled','done','moved','reminder','client_2h','master_2h','review_request'].includes(k))error(400,'Неизвестный системный текст');out[k]={};for(const l of LANGS){const t=clean(translations?.[l],300);if(t)out[k][l]=t}}return out}
 if(key==='flags'){const out={};for(const k of ['reviews','help']){const f=v?.[k];if(!f||!['all','test','off','specialists','percent'].includes(f.mode)||!Array.isArray(f.users)||f.users.length>100||f.users.some(x=>!/^\d{1,20}$/.test(String(x))))error(400,'Проверьте переключатели функций');if(f.mode==='percent'&&(!Number.isInteger(f.percent)||f.percent<0||f.percent>100))error(400,'От 0 до 100 процентов');if(f.mode==='specialists'&&(!Array.isArray(f.companies)||f.companies.length>100||f.companies.some(x=>!/^[-a-zA-Z0-9]{1,80}$/.test(x))))error(400,'Проверьте специалистов');out[k]={mode:f.mode,users:[...new Set(f.users.map(String))],...(f.mode==='percent'?{percent:f.percent}:{}),...(f.mode==='specialists'?{companies:f.companies}:{} )}}return out}
 if(key==='notification_intervals'){if(!v||v.client_24h!==24||v.client_2h!==2||v.master_2h!==2)error(400,'В этой версии поддерживаются интервалы 24 и 2 часа');const minute=v.master_reminder_minutes??60,retry=v.retry_seconds??300;if(!Number.isInteger(minute)||minute<15||minute>180||!Number.isInteger(retry)||retry<60||retry>3600)error(400,'Дополнительное напоминание: 15–180 минут, повтор: 60–3600 секунд');return {client_24h:24,client_2h:2,master_2h:2,master_reminder_minutes:minute,retry_seconds:retry}}
 if(key==='announcement'){if(typeof v?.enabled!=='boolean'||!LANGS.includes(v.language)||!['all','specialists','clients'].includes(v.audience)||!Number.isInteger(v.starts_at)||!Number.isInteger(v.ends_at)||v.starts_at<0||v.ends_at<v.starts_at||v.ends_at>Math.floor(Date.now()/1000)+366*86400||v.enabled&&!clean(v.text,800))error(400,'Проверьте баннер и время показа');return {enabled:v.enabled,text:clean(v.text,800),language:v.language,audience:v.audience,starts_at:v.starts_at,ends_at:v.ends_at}}
 error(400,'Эта настройка недоступна');
}
export const auditStatement=(db,actor,action,target,before,after)=>db.prepare('INSERT INTO admin_audit VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,target,JSON.stringify(before),JSON.stringify(after),stamp());
export async function enforceAccount(db,id){if((await db.prepare('SELECT blocked FROM account_controls WHERE user_id=?').bind(id).first())?.blocked)error(403,'Доступ к аккаунту приостановлен. Обратитесь в поддержку')}
export async function writeLimit(db,id){const window=Math.floor(stamp()/60);const r=await db.prepare('INSERT INTO api_limits VALUES(?,?,1) ON CONFLICT(user_id,window) DO UPDATE SET n=n+1 RETURNING n').bind(id,window).first();if(r.n>60)error(429,'Слишком много действий. Попробуйте через минуту')}
export async function specialistAvailable(db,id){if(await db.prepare('SELECT 1 FROM subscription_freezes WHERE company_id=?').bind(id).first())error(403,'Приём новых записей временно приостановлен');if((await db.prepare('SELECT disabled FROM specialist_controls WHERE company_id=?').bind(id).first())?.disabled)error(403,'Приём новых записей временно приостановлен');if((await db.prepare("SELECT value FROM service_config WHERE key='billing_enforce'").first())?.value==='1'){const s=await db.prepare('SELECT trial_ends_at,paid_until FROM subscriptions WHERE company_id=?').bind(id).first();if(s&&stamp()>=Math.max(Number(s.trial_ends_at||0),Number(s.paid_until||0)))error(403,'Приём новых записей на паузе: у специалиста закончился доступ')}}
export async function applyNotificationText(db,payload){if(!payload?.takt)return payload;const c=await config(db),m=payload.takt,t=customText(c,m.event,m.lang||'ru','');if(t)payload.text=payload.text.replace(/^[^\n]+/,t.replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x])));return payload}
export async function publicConfig(db,id='',env={}){const c=await config(db),owned=await db.prepare('SELECT company_id FROM memberships WHERE user_id=?').bind(String(id)).first(),invited=await db.prepare('SELECT company_id FROM client_links WHERE user_id=? ORDER BY created_at DESC LIMIT 1').bind(String(id)).first();const root=String(env.ADMIN_ID||String(env.SUPERADMIN_IDS||'').split(',')[0]||'');const contact=root?(await db.prepare('SELECT username FROM telegram_profiles WHERE user_id=?').bind(root).first())?.username:'';return {...c,support:c.support||contact||'',flags:Object.fromEntries(Object.keys(c.flags).map(k=>[k,enabled(c,k,id,owned?.company_id||invited?.company_id)]))}}
export async function adminApi(req,env,user,h){const u=new URL(req.url),p=u.pathname;if(!p.startsWith('/api/v10/admin/'))return null;const db=env.DB,adminBody=req.method==='GET'?null:await h.body(req.clone());await requireLegacyAdmin(req,env,user,adminBody);
 if(p==='/api/v10/admin/config'&&req.method==='GET'){const c=await config(db),role=await adminRole(db,env,user.id);return h.json(role==='FINANCE'?{tariff:c.tariff}:role==='CONTENT'?Object.fromEntries(Object.entries(c).filter(([k])=>['texts','documents','support','languages'].includes(k))):c)}
 if(p==='/api/v10/admin/config'&&req.method==='POST'){const b=await h.body(req);if(b.confirm!==true)error(400,'Подтвердите изменение');const before=await config(db),v=validateConfig(b.key,b.value);await db.batch([...(b.key==='tariff'?[db.prepare('INSERT OR IGNORE INTO paid_terms SELECT company_id,?,paid_until FROM subscriptions WHERE paid_until>?').bind(JSON.stringify(validateConfig('tariff',before.tariff)),stamp())]:[]),db.prepare('INSERT INTO service_config VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(b.key,JSON.stringify(v),stamp(),user.id),auditStatement(db,user.id,'config',b.key,before[b.key],v)]);return h.json({ok:true})}
 if(p==='/api/v10/admin/users'&&req.method==='GET'){const q='%'+clean(u.searchParams.get('q')||'',80)+'%',rows=(await db.prepare(`SELECT p.user_id,p.username,p.first_name,p.last_name,a.first_seen,a.last_seen,s.language,s.role,COALESCE(x.blocked,0) blocked,(SELECT COUNT(*) FROM bookings b WHERE b.user_id=p.user_id) bookings FROM telegram_profiles p LEFT JOIN account_activity a ON a.user_id=p.user_id LEFT JOIN user_app_settings s ON s.user_id=p.user_id LEFT JOIN account_controls x ON x.user_id=p.user_id WHERE p.user_id LIKE ? OR p.username LIKE ? OR p.first_name||' '||p.last_name LIKE ? ORDER BY COALESCE(a.last_seen,p.updated_at) DESC LIMIT 100`).bind(q,q,q).all()).results;return h.json(rows)}
 if(p==='/api/v10/admin/user'&&req.method==='POST'){const b=await h.body(req),id=clean(b.user_id,30);if(b.confirm!==true||typeof b.blocked!=='boolean'||!/^[0-9]+$/.test(id)||id===mainAdmin(env))error(400,'Проверьте действие');if(!await db.prepare('SELECT 1 FROM telegram_profiles WHERE user_id=?').bind(id).first())error(404,'Пользователь не найден');const old=await db.prepare('SELECT * FROM account_controls WHERE user_id=?').bind(id).first();await db.batch([db.prepare('INSERT INTO account_controls VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET blocked=excluded.blocked,updated_at=excluded.updated_at').bind(id,+b.blocked,stamp()),auditStatement(db,user.id,'account',id,old,{blocked:b.blocked})]);return h.json({ok:true})}
 if(p==='/api/v10/admin/specialists'&&req.method==='GET'){const q='%'+clean(u.searchParams.get('q')||'',80)+'%',filter=u.searchParams.get('status')||'',rows=(await db.prepare(`SELECT c.id,c.name,c.category,c.active,m.user_id,p.username,s.language,r.created_at,z.trial_ends_at,z.paid_until,COALESCE(x.disabled,0) disabled,(SELECT COUNT(*) FROM services WHERE company_id=c.id) services,(SELECT COUNT(*) FROM bookings WHERE company_id=c.id) bookings FROM companies c JOIN memberships m ON m.company_id=c.id LEFT JOIN telegram_profiles p ON p.user_id=m.user_id LEFT JOIN user_app_settings s ON s.user_id=m.user_id LEFT JOIN registrations r ON r.company_id=c.id LEFT JOIN subscriptions z ON z.company_id=c.id LEFT JOIN specialist_controls x ON x.company_id=c.id WHERE c.name LIKE ? OR c.id LIKE ? OR p.username LIKE ? ORDER BY r.created_at DESC LIMIT 100`).bind(q,q,q).all()).results;const t=stamp();return h.json(rows.map(r=>({...r,status:r.disabled?'disabled':r.paid_until>t?'active':r.trial_ends_at>t?'trial':'expired'})).filter(r=>!filter||r.status===filter))}
 if(p==='/api/v10/admin/specialist'&&req.method==='POST'){const b=await h.body(req),id=clean(b.company_id,80);if(!await db.prepare('SELECT 1 FROM companies c JOIN memberships m ON m.company_id=c.id WHERE c.id=?').bind(id).first())error(404,'Специалист не найден');if(b.confirm!==true)error(400,'Подтвердите действие');const ops=[];let before,after;
 if(b.action==='disable'||b.action==='restore'){before=await db.prepare('SELECT * FROM specialist_controls WHERE company_id=?').bind(id).first();after={disabled:b.action==='disable'};ops.push(db.prepare('INSERT INTO specialist_controls VALUES(?,?,?) ON CONFLICT(company_id) DO UPDATE SET disabled=excluded.disabled,updated_at=excluded.updated_at').bind(id,+after.disabled,stamp()))}
 else if(b.action==='extend'||b.action==='trial'){if(!Number.isInteger(b.days)||b.days<1||b.days>366)error(400,'От 1 до 366 дней');const c=await config(db),t=stamp();await db.prepare('INSERT OR IGNORE INTO subscriptions VALUES(?,?,?,?,NULL,?)').bind(id,t,t+c.tariff.trial_days*86400,'trial',t).run();before=await db.prepare('SELECT * FROM subscriptions WHERE company_id=?').bind(id).first();const column=b.action==='trial'?'trial_ends_at':'paid_until',until=Math.max(t,before[column]||0)+b.days*86400;after={[column]:until};ops.push(db.prepare(`UPDATE subscriptions SET ${column}=?,status=?,updated_at=? WHERE company_id=?`).bind(until,b.action==='trial'?'trial':'active',t,id))}else error(400,'Неизвестное действие');await db.batch([...ops,auditStatement(db,user.id,b.action,id,before,after)]);return h.json({ok:true})}
 if(p==='/api/v10/admin/audit'&&req.method==='GET')return h.json((await db.prepare('SELECT * FROM admin_audit ORDER BY created_at DESC,rowid DESC LIMIT 100').all()).results);
 if(p==='/api/v10/admin/broadcast/preview'&&req.method==='POST'){const b=await h.body(req),message=clean(b.text,3500);if(!message)error(400,'Введите сообщение');let ids;
 if(b.audience==='specialists')ids=(await db.prepare('SELECT DISTINCT m.user_id FROM memberships m JOIN telegram_contacts t ON t.user_id=m.user_id WHERE t.state=\'allowed\'').all()).results.map(r=>r.user_id);
 else if(b.audience==='clients')ids=(await db.prepare('SELECT DISTINCT l.user_id FROM client_links l JOIN telegram_contacts t ON t.user_id=l.user_id WHERE t.state=\'allowed\'').all()).results.map(r=>r.user_id);
 else if(b.audience==='selected'&&Array.isArray(b.ids)&&b.ids.length<=100){ids=[...new Set(b.ids.map(String))];if(ids.some(i=>!/^\d{1,20}$/.test(i)))error(400,'Проверьте получателей');if((await db.prepare("SELECT COUNT(*) n FROM telegram_contacts WHERE state='allowed' AND user_id IN ("+ids.map(()=>'?').join(',')+")").bind(...ids).first()).n!==ids.length)error(400,'Получатель ещё не активировал бота')}else error(400,'Выберите аудиторию');
 if(b.filters){const f=b.filters;if(b.audience==='clients'&&(f.status||f.registered_after))error(400,'Фильтры подписки и регистрации доступны для специалистов');if(f.language&&!LANGS.includes(f.language))error(400,'Проверьте язык');if(f.status&&!['active','trial','expiring'].includes(f.status))error(400,'Проверьте статус');if(f.registered_after&&(!Number.isInteger(f.registered_after)||f.registered_after<0))error(400,'Проверьте дату');const allowed=b.audience==='clients'?(await db.prepare("SELECT user_id FROM user_app_settings WHERE (?='' OR language=?)").bind(f.language||'',f.language||'').all()).results.map(r=>r.user_id):(await db.prepare(`SELECT DISTINCT m.user_id FROM memberships m LEFT JOIN subscriptions z ON z.company_id=m.company_id LEFT JOIN user_app_settings s ON s.user_id=m.user_id LEFT JOIN registrations r ON r.company_id=m.company_id WHERE (?='' OR s.language=?) AND (?=0 OR r.created_at>=?) AND (?='' OR ?='active' AND z.paid_until>unixepoch() OR ?='trial' AND z.trial_ends_at>unixepoch() AND COALESCE(z.paid_until,0)<=unixepoch() OR ?='expiring' AND MAX(COALESCE(z.paid_until,0),z.trial_ends_at) BETWEEN unixepoch() AND unixepoch()+7*86400)`).bind(f.language||'',f.language||'',f.registered_after||0,f.registered_after||0,f.status||'',f.status||'',f.status||'',f.status||'').all()).results.map(r=>r.user_id);ids=ids.filter(id=>allowed.includes(id))}
 ids=ids.filter(i=>i!==user.id);if(!ids.length)error(400,'Нет доступных получателей');if(ids.length>10000)error(400,'Выберите меньшую аудиторию');const id=crypto.randomUUID(),token=crypto.randomUUID();await db.prepare('INSERT INTO admin_broadcasts(id,actor,text,recipients,token,created_at) VALUES(?,?,?,?,?,?)').bind(id,user.id,message,JSON.stringify(ids),token,stamp()).run();return h.json({id,token,text:message,count:ids.length})}
 if(p==='/api/v10/admin/broadcast/send'&&req.method==='POST'){const b=await h.body(req),r=await db.prepare('SELECT * FROM admin_broadcasts WHERE id=? AND actor=? AND token=?').bind(clean(b.id,80),user.id,clean(b.token,80)).first();if(!r||b.confirm!==true)error(400,'Сначала проверьте предпросмотр');if(r.status==='queued')return h.json({ok:true,count:JSON.parse(r.recipients).length});if(r.created_at<stamp()-3600)error(409,'Предпросмотр устарел');const result=await db.batch([db.prepare("UPDATE admin_broadcasts SET status='queued',sent_at=? WHERE id=? AND status='preview'").bind(stamp(),r.id),db.prepare("INSERT OR IGNORE INTO outbox(id,chat_id,text,created_at) SELECT 'broadcast:'||?||':'||value,value,?,? FROM json_each(?) WHERE EXISTS(SELECT 1 FROM admin_broadcasts WHERE id=? AND status='queued')").bind(r.id,r.text,stamp(),r.recipients,r.id),auditStatement(db,user.id,'broadcast',r.id,null,{count:JSON.parse(r.recipients).length})]);return h.json({ok:true,count:JSON.parse(r.recipients).length})}
 error(404,'Раздел не найден');
}

export async function effectiveTariff(db,id){const row=await db.prepare('SELECT value FROM paid_terms WHERE company_id=? AND effective_until>?').bind(id,stamp()).first();return row?JSON.parse(row.value):(await config(db)).tariff}
