import {adminRole,requireAdmin,permissions} from './control-auth.js';
import {config,mainAdmin,validateConfig,auditStatement,effectiveTariff} from './v10.js';
import {overview} from './v5.js';
import {translationCatalog} from '../public/i18n.js';
export const schema11=[
`DROP TRIGGER IF EXISTS blocked_insert_guard`,
`CREATE TRIGGER blocked_insert_guard BEFORE INSERT ON blocked_slots WHEN EXISTS(SELECT 1 FROM blocked_slots WHERE company_id=NEW.company_id AND starts_at<NEW.ends_at AND ends_at>NEW.starts_at) BEGIN SELECT RAISE(ABORT,'SLOT_TAKEN'); END`,
`DROP TRIGGER IF EXISTS booking_update_guard`,
`CREATE TRIGGER booking_update_guard BEFORE UPDATE OF starts_at,ends_at,status ON bookings WHEN NEW.status IN ('pending','confirmed') AND (EXISTS(SELECT 1 FROM bookings WHERE company_id=NEW.company_id AND id<>NEW.id AND status IN ('pending','confirmed') AND starts_at<NEW.ends_at AND ends_at>NEW.starts_at) OR ((NEW.starts_at<>OLD.starts_at OR NEW.ends_at<>OLD.ends_at OR OLD.status NOT IN ('pending','confirmed')) AND EXISTS(SELECT 1 FROM blocked_slots WHERE company_id=NEW.company_id AND starts_at<NEW.ends_at AND ends_at>NEW.starts_at))) BEGIN SELECT RAISE(ABORT,'SLOT_TAKEN'); END`,
`CREATE TABLE IF NOT EXISTS paid_terms(company_id TEXT PRIMARY KEY REFERENCES companies(id),value TEXT NOT NULL,effective_until INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS tariff_catalog(id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,period_days INTEGER NOT NULL,trial_days INTEGER NOT NULL,description TEXT NOT NULL,active INTEGER NOT NULL,limits TEXT NOT NULL)`,
`CREATE TRIGGER IF NOT EXISTS booking_plan_limit BEFORE INSERT ON bookings WHEN COALESCE((SELECT json_extract(value,'$.limits.bookings_month') FROM paid_terms WHERE company_id=NEW.company_id AND effective_until>unixepoch()),(SELECT json_extract(value,'$.limits.bookings_month') FROM service_config WHERE key='tariff'),0)>0 AND (SELECT COUNT(*) FROM bookings WHERE company_id=NEW.company_id AND strftime('%Y-%m',created_at,'unixepoch')=strftime('%Y-%m',NEW.created_at,'unixepoch'))>=COALESCE((SELECT json_extract(value,'$.limits.bookings_month') FROM paid_terms WHERE company_id=NEW.company_id AND effective_until>unixepoch()),(SELECT json_extract(value,'$.limits.bookings_month') FROM service_config WHERE key='tariff'),0) AND NOT EXISTS(SELECT 1 FROM bookings WHERE company_id=NEW.company_id AND user_id=NEW.user_id AND request_key=NEW.request_key) BEGIN SELECT RAISE(ABORT,'PLAN_LIMIT'); END`,
`CREATE TABLE IF NOT EXISTS admin_operation_receipts(id TEXT PRIMARY KEY,actor TEXT NOT NULL,fingerprint TEXT NOT NULL,created_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS admin_roles(user_id TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('SUPPORT','FINANCE','CONTENT')),active INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS subscription_freezes(company_id TEXT PRIMARY KEY REFERENCES companies(id),started_at INTEGER NOT NULL,remaining_paid INTEGER NOT NULL,remaining_trial INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS promos(code TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('percent','amount')),value INTEGER NOT NULL,expires_at INTEGER NOT NULL,max_uses INTEGER NOT NULL,per_user INTEGER NOT NULL DEFAULT 1,new_only INTEGER NOT NULL DEFAULT 0,tariff TEXT NOT NULL DEFAULT 'Takt',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS promo_uses(id TEXT PRIMARY KEY,code TEXT NOT NULL REFERENCES promos(code),company_id TEXT NOT NULL REFERENCES companies(id),user_id TEXT NOT NULL,discount INTEGER NOT NULL,price INTEGER NOT NULL,created_at INTEGER NOT NULL,UNIQUE(id))`,
`CREATE TABLE IF NOT EXISTS content_faq(id TEXT PRIMARY KEY,category TEXT NOT NULL,question TEXT NOT NULL,answer TEXT NOT NULL,language TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS content_translations(key TEXT NOT NULL,language TEXT NOT NULL,value TEXT NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(key,language))`,
`CREATE TABLE IF NOT EXISTS funnel_counts(company_id TEXT NOT NULL,day TEXT NOT NULL,stage TEXT NOT NULL,n INTEGER NOT NULL,PRIMARY KEY(company_id,day,stage))`,
`CREATE TABLE IF NOT EXISTS funnel_seen(user_id TEXT NOT NULL,company_id TEXT NOT NULL,day TEXT NOT NULL,stage TEXT NOT NULL,PRIMARY KEY(user_id,company_id,day,stage))`
];
const now=()=>Math.floor(Date.now()/1000),err=(status,message)=>{throw Object.assign(new Error(message),{status})},text=(v,n=500)=>typeof v==='string'?v.trim().slice(0,n):'',yes=b=>{if(b.confirm!==true)err(400,'Подтвердите действие')},integer=(v,min,max)=>{if(!Number.isInteger(v)||v<min||v>max)err(400,'Проверьте числовое значение');return v};
const csv=rows=>{const keys=rows.length?Object.keys(rows[0]):[];const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};return '\uFEFF'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(';')).join('\r\n')};
export async function publicContent(db,language='ru'){const c=await config(db);return {announcement:c.announcement,translations:(await db.prepare('SELECT key,value FROM content_translations WHERE language=?').bind(language).all()).results,faq:(await db.prepare('SELECT id,category,question,answer FROM content_faq WHERE language=? AND active=1 ORDER BY position,id').bind(language).all()).results}}
async function detailed(db,id){const c=await db.prepare(`SELECT c.id,c.name,c.category,c.tagline,c.address,p.username,s.language,r.created_at,a.last_seen,z.trial_started_at,z.trial_ends_at,z.paid_until,z.status,(SELECT COUNT(DISTINCT user_id) FROM client_links WHERE company_id=c.id) clients,(SELECT COUNT(*) FROM bookings WHERE company_id=c.id) bookings,(SELECT COUNT(*) FROM bookings WHERE company_id=c.id AND status='cancelled') cancelled,(SELECT COUNT(*) FROM bookings b WHERE b.company_id=c.id AND b.status='done' AND NOT EXISTS(SELECT 1 FROM booking_outcomes o WHERE o.booking_id=b.id AND o.outcome='no_show')) done,(SELECT COUNT(*) FROM booking_outcomes o JOIN bookings b ON b.id=o.booking_id WHERE b.company_id=c.id AND o.outcome='no_show') no_show,(SELECT COUNT(*) FROM reviews WHERE company_id=c.id) reviews FROM companies c JOIN memberships m ON m.company_id=c.id LEFT JOIN telegram_profiles p ON p.user_id=m.user_id LEFT JOIN user_app_settings s ON s.user_id=m.user_id LEFT JOIN registrations r ON r.company_id=c.id LEFT JOIN account_activity a ON a.user_id=m.user_id LEFT JOIN subscriptions z ON z.company_id=c.id WHERE c.id=?`).bind(id).first();if(!c)err(404,'Специалист не найден');return {...c,tariff:(await config(db)).tariff.name,history:(await db.prepare('SELECT actor,action,before_value,after_value,created_at FROM admin_audit WHERE target=? ORDER BY created_at DESC LIMIT 30').bind(id).all()).results,delivery_errors:(await db.prepare(`SELECT d.state,COUNT(*) n FROM delivery_state d JOIN outbox o ON o.id=d.id WHERE json_valid(o.text) AND json_extract(o.text,'$.takt.company')=? AND d.state IN ('failed','blocked','unknown','retry') GROUP BY d.state`).bind(id).all()).results}}
async function handleAdmin11(req,env,user,h){const u=new URL(req.url),p=u.pathname;if(!p.startsWith('/api/v11/admin/'))return null;const db=env.DB,role=await requireAdmin(db,env,user.id,'overview'),check=permission=>requireAdmin(db,env,user.id,permission),read=req.method==='GET',b=read?null:await h.body(req),suffix=p.slice('/api/v11/admin/'.length);
 if(suffix==='overview'&&read){const o=await overview(db),allowed=permissions[role];return h.json({role,permissions:allowed,...(allowed.includes('support')?{recentSupport:o.recentSupport}:{}),totals:o.totals,bookingStats:o.bookingStats,...(allowed.includes('finance')?{subscriptions:o.subscriptions}:{}),...(allowed.includes('system')?{delivery:o.delivery,errors:o.errors,tasks:o.tasks,bot_configured:!!env.BOT_TOKEN}:{}),checked_at:o.checked_at})}
 if(suffix==='roles'){await check('roles');if(read)return h.json({owner:mainAdmin(env),roles:(await db.prepare('SELECT * FROM admin_roles ORDER BY user_id').all()).results});yes(b);const id=text(b.user_id,30);if(!/^\d{1,20}$/.test(id)||id===mainAdmin(env)||!['SUPPORT','FINANCE','CONTENT'].includes(b.role)||typeof b.active!=='boolean')err(400,'Проверьте роль и пользователя');if(!await db.prepare('SELECT 1 FROM telegram_profiles WHERE user_id=?').bind(id).first())err(404,'Пользователь должен сначала открыть Takt');const old=await db.prepare('SELECT * FROM admin_roles WHERE user_id=?').bind(id).first();await db.batch([db.prepare('INSERT INTO admin_roles VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET role=excluded.role,active=excluded.active,updated_at=excluded.updated_at').bind(id,b.role,+b.active,now()),auditStatement(db,user.id,'role',id,old,b)]);return h.json({ok:true})}
 if(suffix==='search'&&read){const q='%'+text(u.searchParams.get('q'),80)+'%',can=permissions[role],r={};if(can.includes('users')){r.specialists=(await db.prepare('SELECT c.id,c.name,p.username FROM companies c JOIN memberships m ON m.company_id=c.id LEFT JOIN telegram_profiles p ON p.user_id=m.user_id WHERE c.name LIKE ? OR p.username LIKE ? OR c.id LIKE ? LIMIT 30').bind(q,q,q).all()).results;r.clients=(await db.prepare("SELECT DISTINCT p.user_id,p.first_name,p.last_name,p.username FROM telegram_profiles p JOIN client_links l ON l.user_id=p.user_id WHERE p.user_id LIKE ? OR p.username LIKE ? OR COALESCE(p.first_name,'')||' '||COALESCE(p.last_name,'') LIKE ? LIMIT 30").bind(q,q,q).all()).results;r.bookings=(await db.prepare('SELECT id,company_id,name,service_name,starts_at,status FROM bookings WHERE id LIKE ? OR name LIKE ? OR service_name LIKE ? LIMIT 30').bind(q,q,q).all()).results;r.services=(await db.prepare('SELECT id,company_id,name,price FROM services WHERE name LIKE ? OR id LIKE ? LIMIT 30').bind(q,q).all()).results}else if(can.includes('finance'))r.specialists=(await db.prepare('SELECT c.id,c.name,z.status,z.paid_until,z.trial_ends_at FROM companies c JOIN subscriptions z ON z.company_id=c.id WHERE c.name LIKE ? OR c.id LIKE ? LIMIT 30').bind(q,q).all()).results;return h.json(r)}
 if(suffix==='specialist'&&read){await check('users');return h.json(await detailed(db,text(u.searchParams.get('company'),80)))}
 if(suffix==='preview'&&read){await check('preview');const id=text(u.searchParams.get('company'),80),mode=u.searchParams.get('mode')||'specialist',c=await detailed(db,id);if(!['specialist','client'].includes(mode))err(400,'Выберите режим просмотра');const client=text(u.searchParams.get('client'),30);if(mode==='client'&&!await db.prepare('SELECT 1 FROM client_links WHERE company_id=? AND user_id=?').bind(id,client).first())err(404,'Связь клиента со специалистом не найдена');const data={readonly:true,mode,company:{id:c.id,name:c.name,category:c.category,tagline:c.tagline,address:c.address},services:(await db.prepare('SELECT id,name,price,active FROM services WHERE company_id=?').bind(id).all()).results,bookings:(await db.prepare(`SELECT b.id,b.name,b.service_name,b.price,b.starts_at,b.ends_at,b.status,o.outcome FROM bookings b LEFT JOIN booking_outcomes o ON o.booking_id=b.id WHERE b.company_id=? ${mode==='client'?'AND b.user_id=?':''} ORDER BY starts_at DESC LIMIT 100`).bind(...(mode==='client'?[id,client]:[id])).all()).results};return h.json(data)}
 if(suffix==='subscription'&&!read){await check('finance');yes(b);if(!/^[a-zA-Z0-9-]{8,80}$/.test(b.request_key||''))err(400,'Повторите действие');const operationId=user.id+':'+b.request_key,fingerprint=JSON.stringify([b.company_id,b.action,b.days,b.until]);const previous=await db.prepare('SELECT * FROM admin_operation_receipts WHERE id=?').bind(operationId).first();if(previous){if(previous.fingerprint!==fingerprint)err(409,'Ключ уже использован для другого действия');return h.json({ok:true})}const receipt=db.prepare('INSERT INTO admin_operation_receipts VALUES(?,?,?,?)').bind(operationId,user.id,fingerprint,now());const id=text(b.company_id,80);if(!await db.prepare('SELECT 1 FROM memberships WHERE company_id=?').bind(id).first())err(404,'Специалист не найден');const cfg=await config(db);await db.prepare('INSERT OR IGNORE INTO subscriptions VALUES(?,?,?,?,NULL,?)').bind(id,now(),now()+cfg.tariff.trial_days*86400,'trial',now()).run();const old=await db.prepare('SELECT * FROM subscriptions WHERE company_id=?').bind(id).first();let statement,after;
 if(['gift','extend','trial'].includes(b.action)){const days=integer(b.days,1,366),field=b.action==='trial'?'trial_ends_at':'paid_until';after={[field]:Math.max(now(),old[field]||0)+days*86400};statement=db.prepare(`UPDATE subscriptions SET ${field}=MAX(?,COALESCE(${field},0))+?,status=?,updated_at=? WHERE company_id=?`).bind(now(),days*86400,field==='paid_until'?'active':'trial',now(),id)}
 else if(b.action==='end'){const t=integer(b.until,now()-86400,now()+5*366*86400);after={paid_until:t};statement=db.prepare("UPDATE subscriptions SET paid_until=?,status=?,updated_at=? WHERE company_id=?").bind(t,t>now()?'active':'expired',now(),id)}
 else if(b.action==='freeze'){if(await db.prepare('SELECT 1 FROM subscription_freezes WHERE company_id=?').bind(id).first())return h.json({ok:true});after={frozen:true};await db.batch([receipt,db.prepare('INSERT INTO subscription_freezes VALUES(?,?,?,?)').bind(id,now(),Math.max(0,(old.paid_until||0)-now()),Math.max(0,old.trial_ends_at-now())),db.prepare("UPDATE subscriptions SET status='grace',updated_at=? WHERE company_id=?").bind(now(),id),auditStatement(db,user.id,'subscription-freeze',id,old,after)]);return h.json({ok:true})}
 else if(b.action==='restore'){const f=await db.prepare('SELECT * FROM subscription_freezes WHERE company_id=?').bind(id).first();if(!f)return h.json({ok:true});after={paid_until:f.remaining_paid?now()+f.remaining_paid:old.paid_until,trial_ends_at:f.remaining_trial?now()+f.remaining_trial:old.trial_ends_at};await db.batch([receipt,db.prepare('UPDATE subscriptions SET paid_until=?,trial_ends_at=?,status=?,updated_at=? WHERE company_id=?').bind(after.paid_until,after.trial_ends_at,f.remaining_paid?'active':f.remaining_trial?'trial':'expired',now(),id),db.prepare('UPDATE paid_terms SET effective_until=? WHERE company_id=? AND effective_until>=?').bind(after.paid_until,id,f.started_at),db.prepare('DELETE FROM subscription_freezes WHERE company_id=?').bind(id),auditStatement(db,user.id,'subscription-restore',id,old,after)]);return h.json({ok:true})}else err(400,'Неизвестное действие');await db.batch([receipt,statement,auditStatement(db,user.id,'subscription-'+b.action,id,old,after)]);return h.json({ok:true})}
 if(suffix==='plans'){await check('finance');if(read)return h.json((await db.prepare('SELECT * FROM tariff_catalog ORDER BY name').all()).results);yes(b);const id=text(b.id,80)||crypto.randomUUID(),v=validateConfig('tariff',{...b,enabled:b.active});const old=await db.prepare('SELECT * FROM tariff_catalog WHERE id=?').bind(id).first();await db.batch([db.prepare('INSERT INTO tariff_catalog VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,price=excluded.price,period_days=excluded.period_days,trial_days=excluded.trial_days,description=excluded.description,active=excluded.active,limits=excluded.limits').bind(id,v.name,v.price,v.period_days,v.trial_days,v.description,+b.active,JSON.stringify(v.limits)),auditStatement(db,user.id,'plan',id,old,v)]);return h.json({ok:true,id})}
 if(suffix==='plan-default'&&!read){await check('finance');yes(b);const row=await db.prepare('SELECT * FROM tariff_catalog WHERE id=? AND active=1').bind(text(b.id,80)).first();if(!row)err(404,'Тариф недоступен');const before=(await config(db)).tariff,v=validateConfig('tariff',{...row,limits:JSON.parse(row.limits),enabled:true});await db.batch([db.prepare('INSERT OR IGNORE INTO paid_terms SELECT company_id,?,paid_until FROM subscriptions WHERE paid_until>?').bind(JSON.stringify(validateConfig('tariff',before)),now()),db.prepare('INSERT INTO service_config VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind('tariff',JSON.stringify(v),now(),user.id),auditStatement(db,user.id,'config','tariff',before,v)]);return h.json({ok:true})}
 if(suffix==='promos'){await check('finance');if(read)return h.json({promos:(await db.prepare('SELECT * FROM promos ORDER BY created_at DESC').all()).results,uses:(await db.prepare('SELECT * FROM promo_uses ORDER BY created_at DESC LIMIT 100').all()).results});yes(b);const code=text(b.code,32).toUpperCase();if(!/^[A-Z0-9_-]{3,32}$/.test(code)||!['percent','amount'].includes(b.kind)||typeof b.active!=='boolean')err(400,'Проверьте промокод');integer(b.value,1,b.kind==='percent'?100:100000);integer(b.max_uses,1,100000);integer(b.expires_at,now()+1,now()+5*366*86400);integer(b.per_user,1,12);const old=await db.prepare('SELECT * FROM promos WHERE code=?').bind(code).first();await db.batch([db.prepare('INSERT INTO promos VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET kind=excluded.kind,value=excluded.value,expires_at=excluded.expires_at,max_uses=excluded.max_uses,per_user=excluded.per_user,new_only=excluded.new_only,tariff=excluded.tariff,active=excluded.active').bind(code,b.kind,b.value,b.expires_at,b.max_uses,b.per_user,+!!b.new_only,text(b.tariff,60)||'Takt',+b.active,now()),auditStatement(db,user.id,'promo',code,old,b)]);return h.json({ok:true})}
 if(suffix==='faq'){await check('content');if(read)return h.json((await db.prepare('SELECT * FROM content_faq ORDER BY language,position').all()).results);yes(b);const id=text(b.id,80)||crypto.randomUUID(),question=text(b.question,200),answer=text(b.answer,3000);if(!question||!answer||!['ru','kk','az','uz'].includes(b.language))err(400,'Заполните вопрос, ответ и язык');const old=await db.prepare('SELECT * FROM content_faq WHERE id=?').bind(id).first();integer(b.position,0,10000);await db.batch([db.prepare('INSERT INTO content_faq VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,question=excluded.question,answer=excluded.answer,language=excluded.language,position=excluded.position,active=excluded.active').bind(id,text(b.category,80)||'Takt',question,answer,b.language,b.position,+!!b.active),auditStatement(db,user.id,'faq',id,old,b)]);return h.json({ok:true,id})}
 if(suffix==='translations'){await check('content');if(read){const catalog=translationCatalog(),overrides=(await db.prepare('SELECT * FROM content_translations').all()).results;return h.json({catalog,overrides})}yes(b);const catalog=translationCatalog();if(!catalog.some(x=>x.key===b.key)||!['kk','az','uz'].includes(b.language)||!text(b.value,2000))err(400,'Проверьте ключ, язык и перевод');const old=await db.prepare('SELECT * FROM content_translations WHERE key=? AND language=?').bind(b.key,b.language).first();await db.batch([db.prepare('INSERT INTO content_translations VALUES(?,?,?,?) ON CONFLICT(key,language) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind(b.key,b.language,text(b.value,2000),now()),auditStatement(db,user.id,'translation',b.key+':'+b.language,old,b)]);return h.json({ok:true})}
 if(suffix==='rollback'&&!read){await check('manage_config');yes(b);const entry=await db.prepare("SELECT * FROM admin_audit WHERE id=? AND action='config'").bind(text(b.id,80)).first();if(!entry)err(404,'Изменение не найдено');const old=await config(db),previous=validateConfig(entry.target,JSON.parse(entry.before_value));await db.batch([...(entry.target==='tariff'?[db.prepare('INSERT OR IGNORE INTO paid_terms SELECT company_id,?,paid_until FROM subscriptions WHERE paid_until>?').bind(JSON.stringify(validateConfig('tariff',old.tariff)),now())]:[]),db.prepare('INSERT INTO service_config VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(entry.target,JSON.stringify(previous),now(),user.id),auditStatement(db,user.id,'rollback',entry.target,old[entry.target],previous)]);return h.json({ok:true})}
 if(suffix==='delivery'&&read){await check('system');return h.json((await db.prepare(`SELECT o.id,o.chat_id,o.attempts,o.created_at,o.sent_at,o.lease_until,d.state,d.updated_at FROM outbox o LEFT JOIN delivery_state d ON d.id=o.id ORDER BY o.created_at DESC LIMIT 100`).all()).results)}
 if(suffix==='retry'&&!read){await check('system');yes(b);const r=await db.prepare('SELECT o.*,d.state FROM outbox o JOIN delivery_state d ON d.id=o.id WHERE o.id=?').bind(text(b.id,160)).first();if(!r||r.state!=='retry'||r.sent_at||r.attempts>=5)err(409,'Повтор безопасен только для временной ошибки с известным результатом');const changed=await db.prepare('UPDATE outbox SET lease_until=0 WHERE id=? AND attempts<5 AND sent_at IS NULL').bind(r.id).run();if(changed.meta.changes)await auditStatement(db,user.id,'retry',r.id,{lease_until:r.lease_until},{lease_until:0}).run();return h.json({ok:true})}
 if(suffix==='stats'&&read){await check('overview');const stats=await db.prepare(`SELECT (SELECT COUNT(*) FROM registrations) specialists,(SELECT COUNT(*) FROM registrations WHERE created_at>unixepoch()-86400) new_specialists,(SELECT COUNT(DISTINCT m.company_id) FROM memberships m JOIN account_activity a ON a.user_id=m.user_id WHERE a.last_seen>unixepoch()-86400) active1,(SELECT COUNT(DISTINCT m.company_id) FROM memberships m JOIN account_activity a ON a.user_id=m.user_id WHERE a.last_seen>unixepoch()-7*86400) active7,(SELECT COUNT(DISTINCT m.company_id) FROM memberships m JOIN account_activity a ON a.user_id=m.user_id WHERE a.last_seen>unixepoch()-30*86400) active30,(SELECT COUNT(DISTINCT user_id) FROM client_links) clients,(SELECT COUNT(DISTINCT user_id) FROM client_links WHERE created_at>unixepoch()-86400) new_clients,(SELECT COUNT(*) FROM bookings) bookings,(SELECT COUNT(*) FROM subscriptions WHERE paid_until IS NOT NULL) converted,(SELECT COUNT(*) FROM subscriptions) trials,(SELECT COUNT(DISTINCT m.company_id) FROM memberships m JOIN account_activity a ON a.user_id=m.user_id WHERE a.last_seen<unixepoch()-30*86400) inactive30`).first();const retention=await db.prepare(`SELECT COALESCE(100.0*SUM(CASE WHEN a.last_seen>=r.created_at+7*86400 THEN 1 ELSE 0 END)/NULLIF(SUM(r.created_at<=unixepoch()-7*86400),0),0) retention7,COALESCE(100.0*SUM(CASE WHEN a.last_seen>=r.created_at+30*86400 THEN 1 ELSE 0 END)/NULLIF(SUM(r.created_at<=unixepoch()-30*86400),0),0) retention30 FROM registrations r JOIN memberships m ON m.company_id=r.company_id LEFT JOIN account_activity a ON a.user_id=m.user_id`).first();return h.json({...stats,...retention,average:stats.specialists?stats.bookings/stats.specialists:0,conversion:stats.trials?100*stats.converted/stats.trials:0,activityRetention:stats.specialists?100*stats.active30/stats.specialists:0,funnel:(await db.prepare('SELECT stage,SUM(n) n FROM funnel_counts WHERE day>=date(\'now\',\'-30 days\') GROUP BY stage').all()).results})}
 if(suffix==='export'&&read){await check('export');const type=u.searchParams.get('type'),rows=type==='subscriptions'?(await db.prepare('SELECT company_id,status,trial_ends_at,paid_until FROM subscriptions').all()).results:type==='specialists'?(await db.prepare('SELECT c.id,c.name,c.category FROM companies c JOIN memberships m ON m.company_id=c.id').all()).results:type==='stats'?(await db.prepare('SELECT c.id,COUNT(b.id) bookings,SUM(b.status=\'cancelled\') cancelled FROM companies c LEFT JOIN bookings b ON b.company_id=c.id GROUP BY c.id').all()).results:null;if(!rows)err(400,'Выберите экспорт');await auditStatement(db,user.id,'export',type,null,{rows:rows.length}).run();if(u.searchParams.get('format')==='json')return h.json({filename:'takt-'+type+'.csv',content:csv(rows)});return new Response(csv(rows),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="takt-'+type+'.csv"','Cache-Control':'no-store'}})}
 err(404,'Раздел не найден');
}
export async function applyPromo(db,user,b){if(!/^[a-zA-Z0-9-]{8,80}$/.test(b.request_key||''))err(400,'Повторите действие');const code=text(b.code,32).toUpperCase(),id=text(b.company_id,80);if(!await db.prepare('SELECT 1 FROM memberships WHERE company_id=? AND user_id=?').bind(id,user.id).first())err(403,'Нет доступа');const p=await db.prepare('SELECT * FROM promos WHERE code=?').bind(code).first(),cfg={tariff:await effectiveTariff(db,id)};if(!p||!p.active||p.expires_at<=now()||p.tariff!==cfg.tariff.name)err(400,'Промокод недоступен');if(p.new_only&&await db.prepare('SELECT 1 FROM subscriptions WHERE company_id=? AND paid_until IS NOT NULL').bind(id).first())err(400,'Промокод доступен новым специалистам');const used=await db.prepare('SELECT * FROM promo_uses WHERE id=?').bind(user.id+':'+b.request_key).first();if(used){if(used.code!==code||used.company_id!==id)err(409,'Ключ уже использован');return {ok:true,discount:used.discount,price:used.price,code}}const discount=p.kind==='percent'?Math.floor(cfg.tariff.price*p.value/100):Math.min(cfg.tariff.price,p.value);const result=await db.prepare(`INSERT OR IGNORE INTO promo_uses SELECT ?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM promo_uses WHERE code=?)<? AND (SELECT COUNT(*) FROM promo_uses WHERE code=? AND user_id=?)<?`).bind(user.id+':'+text(b.request_key,80),code,id,user.id,discount,Math.max(0,cfg.tariff.price-discount),now(),code,p.max_uses,code,user.id,p.per_user).run();if(!result.meta.changes){const prior=await db.prepare('SELECT * FROM promo_uses WHERE id=?').bind(user.id+':'+b.request_key).first();if(prior&&prior.code===code&&prior.company_id===id)return {ok:true,discount:prior.discount,price:prior.price,code};err(409,'Промокод уже использован или достигнут лимит');}return {ok:true,discount,price:Math.max(0,cfg.tariff.price-discount),code}}
export async function recordFunnel(db,user,b){if(!['opened','service','time','booking'].includes(b.stage))err(400,'Неизвестный шаг');const id=text(b.company_id,80);if(!await db.prepare('SELECT 1 FROM companies WHERE id=? AND active=1').bind(id).first())err(404,'Специалист не найден');const day=new Date().toISOString().slice(0,10);await db.batch([db.prepare('INSERT OR IGNORE INTO funnel_seen VALUES(?,?,?,?)').bind(user.id,id,day,b.stage),db.prepare('INSERT INTO funnel_counts SELECT ?,?,?,COUNT(*) FROM funnel_seen WHERE company_id=? AND day=? AND stage=? ON CONFLICT(company_id,day,stage) DO UPDATE SET n=excluded.n').bind(id,day,b.stage,id,day,b.stage),db.prepare("DELETE FROM funnel_seen WHERE day<date('now','-31 days')")]);return {ok:true}}

export async function admin11(req,env,user,h){const copy=req.clone();try{return await handleAdmin11(req,env,user,h)}catch(error){if(new URL(req.url).pathname==='/api/v11/admin/subscription'&&req.method==='POST'){const b=await h.body(copy);if(b.request_key){const row=await env.DB.prepare('SELECT * FROM admin_operation_receipts WHERE id=? AND actor=?').bind(user.id+':'+b.request_key,user.id).first();if(row&&row.fingerprint===JSON.stringify([b.company_id,b.action,b.days,b.until]))return h.json({ok:true})}}throw error}}
