import {schema5} from './v5.js';
import {localDate,localMinute,fromLocal,dateShift,zoneLabel} from '../public/time.js';
export {localDate,localMinute,fromLocal,dateShift,zoneLabel};
export const defaults={timezone:'Europe/Moscow',profession:'',telegram:'',format:'salon',min_notice:30,horizon:30,buffer:0,allow_reschedule:true,summary_time:'20:00',venue_name:'',floor:'',room:'',entrance:'',directions:'',map_url:'',notifications:{client_events:true,client_2h:true,master_2h:true,daily_summary:true,created:true,cancelled:true,moved:true,reminders:true,summary:false,master_reminder:false}};
export const schema3=[
...schema5,
`CREATE TABLE IF NOT EXISTS delivery_state(id TEXT PRIMARY KEY REFERENCES outbox(id) ON DELETE CASCADE,state TEXT NOT NULL,updated_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS telegram_updates(id INTEGER PRIMARY KEY,created_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS specialist_options(company_id TEXT PRIMARY KEY REFERENCES companies(id),data TEXT NOT NULL DEFAULT '{}')`,
`CREATE TABLE IF NOT EXISTS specialist_handles(handle TEXT PRIMARY KEY COLLATE NOCASE,company_id TEXT NOT NULL REFERENCES companies(id),created_at INTEGER NOT NULL)`,
`CREATE INDEX IF NOT EXISTS handles_company ON specialist_handles(company_id)`,
...['INSERT','UPDATE OF starts_at,ends_at,status'].map((operation,i)=>`CREATE TRIGGER IF NOT EXISTS booking_buffer_${i} BEFORE ${operation} ON bookings WHEN NEW.status IN ('pending','confirmed') AND EXISTS(SELECT 1 FROM bookings b WHERE b.company_id=NEW.company_id AND b.id<>NEW.id AND b.status IN ('pending','confirmed') AND b.starts_at<NEW.ends_at+COALESCE((SELECT json_extract(data,'$.buffer')*60 FROM specialist_options WHERE company_id=NEW.company_id),0) AND b.ends_at+COALESCE((SELECT json_extract(data,'$.buffer')*60 FROM specialist_options WHERE company_id=NEW.company_id),0)>NEW.starts_at) BEGIN SELECT RAISE(ABORT,'SLOT_TAKEN'); END`)
];
export async function options(db,id){const row=await db.prepare('SELECT data FROM specialist_options WHERE company_id=?').bind(id).first();const x=row?JSON.parse(row.data):{};return {...defaults,...x,notifications:{...defaults.notifications,...x.notifications}}}
const short=(v,n)=>String(v||'').trim().slice(0,n);
export function validateOptions(b,old){const x={...old,...b,notifications:{...old.notifications,...b.notifications}};try{new Intl.DateTimeFormat('en',{timeZone:x.timezone}).format()}catch{throw Object.assign(Error('Выберите часовой пояс'),{status:400})}for(const [k,min,max] of [['min_notice',0,10080],['horizon',1,180],['buffer',0,240]])if(!Number.isInteger(x[k])||x[k]<min||x[k]>max)throw Object.assign(Error('Проверьте правила записи'),{status:400});if(!['salon','visit','online'].includes(x.format))throw Object.assign(Error('Выберите формат работы'),{status:400});if(x.telegram&&!/^@?[a-zA-Z0-9_]{5,32}$/.test(x.telegram))throw Object.assign(Error('Введите Telegram username без ссылки'),{status:400});if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(x.summary_time))throw Object.assign(Error('Выберите время итогов дня'),{status:400});const mapUrl=short(x.map_url,500);if(mapUrl&&!/^https:\/\//i.test(mapUrl))throw Object.assign(Error('Ссылка на карту должна начинаться с https://'),{status:400});return {summary_time:x.summary_time,timezone:x.timezone,profession:short(x.profession,80),telegram:short(x.telegram,33).replace(/^@/,''),format:x.format,min_notice:x.min_notice,horizon:x.horizon,buffer:x.buffer,allow_reschedule:x.allow_reschedule!==false,venue_name:short(x.venue_name,80),floor:short(x.floor,30),room:short(x.room,40),entrance:short(x.entrance,100),directions:short(x.directions,500),map_url:mapUrl,notifications:Object.fromEntries(Object.keys(defaults.notifications).map(k=>[k,x.notifications[k]!==false]))}}
export function publicOptions(c){const {notifications,summary_time,...rest}=c;return rest}
export const shortBase=env=>(env.SHORT_LINK_BASE||env.APP_URL||'https://takt.teymurstudent.workers.dev').replace(/\/$/,'');
export const escHtml=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
export function when(t,zone){return {date:new Date(t*1000).toLocaleDateString('ru-RU',{timeZone:zone,day:'numeric',month:'long'}),time:new Date(t*1000).toLocaleTimeString('ru-RU',{timeZone:zone,hour:'2-digit',minute:'2-digit'})}}
export function messagePayload(b,c,event,admin=false,previous=null){const w=when(b.starts_at,c.timezone),money=new Intl.NumberFormat('ru-RU').format(b.price)+' ₽';const titles={created:admin?'✅ Новая запись':'✅ Вы записаны',confirmed:'✅ Запись подтверждена',cancelled:admin?'❌ Запись отменена':'❌ Запись отменена',done:'Спасибо за встречу 🤍',client_2h:'⏰ До записи осталось 2 часа',master_2h:'⏰ Запись через 2 часа',master_reminder:'⏰ Скоро следующий клиент',reminder:'🔔 Вы придёте на запись?',moved:'🔄 Запись перенесена',attendance_yes:'✅ Клиент подтвердил визит',attendance_no:'❗ Клиент не сможет прийти'};let lines=[`<b>${titles[event]||titles.moved}</b>`,''];if(previous){const old=when(previous,c.timezone);lines.push(`Было: ${old.date} · ${old.time}`,'<b>Стало:</b>')}lines.push(`📅 <b>${event==='reminder'&&localDate(b.starts_at,c.timezone)===dateShift(localDate(Date.now()/1000,c.timezone),1)?'Завтра, ':''}${w.date}</b>`,`🕐 <b>${w.time}</b> · ${escHtml(zoneLabel(c.timezone))}`,'',`✂️ ${escHtml(b.service_name)}`,`👤 ${escHtml(admin?b.name:c.name)}`,`💰 ${money}`);if(admin)lines.push(`📞 ${escHtml(b.phone)}`);else if(c.address)lines.push(`📍 ${escHtml(c.address)}`);if(event==='created'&&!admin&&c.notifications.reminders)lines.push('','Мы напомним вам заранее 🔔');if(event==='cancelled'&&admin)lines.push('','Время снова доступно для записи.');if(event==='reminder')lines.push('','Пожалуйста, подтвердите, что вы придёте.');if(event==='client_2h')lines.push('','До встречи 👋');return {text:lines.join('\n'),parse_mode:'HTML',takt:{booking:b.id,company:b.company_id,start:b.starts_at,event,admin}}}
