import {localDate,localMinute,fromLocal,dateShift,zoneLabel} from '../public/time.js';
export {localDate,localMinute,fromLocal,dateShift,zoneLabel};
export const defaults={timezone:'Europe/Moscow',profession:'',telegram:'',format:'salon',min_notice:30,horizon:30,buffer:0,allow_reschedule:true,notifications:{created:true,cancelled:true,moved:true,reminders:true,summary:false}};
export const schema3=[
`CREATE TABLE IF NOT EXISTS specialist_options(company_id TEXT PRIMARY KEY REFERENCES companies(id),data TEXT NOT NULL DEFAULT '{}')`,
`CREATE TABLE IF NOT EXISTS specialist_handles(handle TEXT PRIMARY KEY COLLATE NOCASE,company_id TEXT NOT NULL REFERENCES companies(id),created_at INTEGER NOT NULL)`,
`CREATE INDEX IF NOT EXISTS handles_company ON specialist_handles(company_id)`,
...['INSERT','UPDATE OF starts_at,ends_at,status'].map((operation,i)=>`CREATE TRIGGER IF NOT EXISTS booking_buffer_${i} BEFORE ${operation} ON bookings WHEN NEW.status IN ('pending','confirmed') AND EXISTS(SELECT 1 FROM bookings b WHERE b.company_id=NEW.company_id AND b.id<>NEW.id AND b.status IN ('pending','confirmed') AND b.starts_at<NEW.ends_at+COALESCE((SELECT json_extract(data,'$.buffer')*60 FROM specialist_options WHERE company_id=NEW.company_id),0) AND b.ends_at+COALESCE((SELECT json_extract(data,'$.buffer')*60 FROM specialist_options WHERE company_id=NEW.company_id),0)>NEW.starts_at) BEGIN SELECT RAISE(ABORT,'SLOT_TAKEN'); END`)
];
export async function options(db,id){const row=await db.prepare('SELECT data FROM specialist_options WHERE company_id=?').bind(id).first();const x=row?JSON.parse(row.data):{};return {...defaults,...x,notifications:{...defaults.notifications,...x.notifications}}}
export function validateOptions(b,old){const x={...old,...b,notifications:{...old.notifications,...b.notifications}};try{new Intl.DateTimeFormat('en',{timeZone:x.timezone}).format()}catch{throw Object.assign(Error('Выберите часовой пояс'),{status:400})}for(const [k,min,max] of [['min_notice',0,10080],['horizon',1,180],['buffer',0,240]])if(!Number.isInteger(x[k])||x[k]<min||x[k]>max)throw Object.assign(Error('Проверьте правила записи'),{status:400});if(!['salon','visit','online'].includes(x.format))throw Object.assign(Error('Выберите формат работы'),{status:400});if(x.telegram&&!/^@?[a-zA-Z0-9_]{5,32}$/.test(x.telegram))throw Object.assign(Error('Введите Telegram username без ссылки'),{status:400});return {timezone:x.timezone,profession:String(x.profession||'').slice(0,80),telegram:String(x.telegram||'').replace(/^@/,''),format:x.format,min_notice:x.min_notice,horizon:x.horizon,buffer:x.buffer,allow_reschedule:x.allow_reschedule!==false,notifications:Object.fromEntries(Object.keys(defaults.notifications).map(k=>[k,x.notifications[k]!==false]))}}
export function publicOptions(c){const {notifications,...rest}=c;return rest}
export const shortBase=env=>(env.SHORT_LINK_BASE||env.APP_URL||'https://takt.teymurstudent.workers.dev').replace(/\/$/,'');
export const escHtml=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
export function when(t,zone){return {date:new Date(t*1000).toLocaleDateString('ru-RU',{timeZone:zone,day:'numeric',month:'long'}),time:new Date(t*1000).toLocaleTimeString('ru-RU',{timeZone:zone,hour:'2-digit',minute:'2-digit'})}}
export function messagePayload(b,c,event,admin=false,previous=null){const w=when(b.starts_at,c.timezone),money=new Intl.NumberFormat('ru-RU').format(b.price)+' ₽';const titles={created:admin?'✅ Новая запись':'✅ Вы записаны',confirmed:'✅ Запись подтверждена',cancelled:'✖️ Запись отменена',done:'Спасибо за встречу 🤍',reminder:'🔔 Напоминаем о записи',moved:'🔄 Запись перенесена'};let lines=[`<b>${titles[event]||titles.moved}</b>`,''];if(previous){const old=when(previous,c.timezone);lines.push(`Было: ${old.date} · ${old.time}`,'<b>Стало:</b>')}lines.push(`📅 <b>${w.date}</b>`,`🕐 <b>${w.time}</b> · ${escHtml(zoneLabel(c.timezone))}`,'',`✂️ ${escHtml(b.service_name)}`,`👤 ${escHtml(admin?b.name:c.name)}`,`💰 ${money}`);if(admin)lines.push(`📞 ${escHtml(b.phone)}`);else if(c.address)lines.push(`📍 ${escHtml(c.address)}`);if(event==='created'&&!admin&&c.notifications.reminders)lines.push('','Мы напомним вам заранее 🔔');if(event==='reminder')lines.push('','До встречи 👋');return {text:lines.join('\n'),parse_mode:'HTML',takt:{booking:b.id,company:b.company_id,start:b.starts_at,event,admin}}}
